## Lecture

In the social and behavioral sciences we're often forced to measure key concepts indirectly. For example, we have no way
of directly quantifying a person's current level of depression, or their innate motivation, or their risk-aversion, or
any of the other myriad psychological features that comprise the human mental state. In truth, we cannot really
*measure* these hypothetical constructs at all, we must *estimate* latent representations thereof (though,
psychometricians still use the language of physical measurement to describe this process).

Furthermore, we can rarely estimate an adequate representation with only a single observed variable (e.g., question on a
survey, score on a test, reading from a sensor). We generally need several observed variables to reliably represent a
single hypothetical construct. For example, we cannot accurately determine someone’s IQ or socio-economic status based
on their response to a single question; we need several questions that each tap into slightly different aspects of IQ or
SES. 

Given multiple items measuring the same hypothetical construct, we can use *factor analysis* to estimate *latent
variables* that represent the unobservable construct. This week we introduce one particular type of factor analysis: 
*confirmatory factor analysis* (CFA).

<!----------------------------------------------------------------------------------------------------------------------
Next week, we will expand on this introduction by fleshing out some more technical details and discussing how to
evaluate the quality of an estimated CFA model. In Weeks 7 and 8, we will combine CFA with path analysis to produce full
*structural equation models*. 
----------------------------------------------------------------------------------------------------------------------->

### Recordings

#### Foundations {-}

<iframe width="560" 
        height="315" 
        src="https://www.youtube.com/embed/Isq3LfWsGw8?si=CGa0V2QyYLBlgBHI"
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; 
               autoplay; 
               clipboard-write; 
               encrypted-media; 
               gyroscope; 
               picture-in-picture; 
               web-share" 
        allowfullscreen>
</iframe>

#### Intuition {-}

<iframe width="560" 
        height="315" 
        src="https://www.youtube.com/embed/HWmnJ_I5Zsw?si=Iz2fotG9t6QcXg4n"
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; 
               autoplay; 
               clipboard-write; 
               encrypted-media; 
               gyroscope; 
               picture-in-picture; 
               web-share" 
        allowfullscreen>
</iframe>

#### Flavors of Factor Analysis {-}

<iframe width="560" 
        height="315" 
        src="https://www.youtube.com/embed/RK1mm9Q_LFQ?si=eVzk-Kz9TWp8Nphb"
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; 
               autoplay; 
               clipboard-write; 
               encrypted-media; 
               gyroscope; 
               picture-in-picture; 
               web-share" 
        allowfullscreen>
</iframe>

#### Path Diagrams {-}

<iframe width="560" 
        height="315" 
        src="https://www.youtube.com/embed/YfSKkeJ2zAw?si=gP495WsL47p9bFle"
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; 
               autoplay; 
               clipboard-write; 
               encrypted-media; 
               gyroscope; 
               picture-in-picture; 
               web-share" 
        allowfullscreen>
</iframe>

#### Degrees of Freedom {-}

<iframe width="560" 
        height="315" 
        src="https://www.youtube.com/embed/lLaECaAfKR4?si=5AcTZPV4QNZ53KP9"
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; 
               autoplay; 
               clipboard-write; 
               encrypted-media; 
               gyroscope; 
               picture-in-picture; 
               web-share" 
        allowfullscreen>
</iframe>

#### Model Identification {-}

<iframe width="560" 
        height="315" 
        src="https://www.youtube.com/embed/3n9RQdIPbxc?si=UuIFkCeMvsuCLxXH"
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; 
               autoplay; 
               clipboard-write; 
               encrypted-media; 
               gyroscope; 
               picture-in-picture; 
               web-share" 
        allowfullscreen>
</iframe>

#### Software Example {-}

<iframe width="560" 
        height="315" 
        src="https://www.youtube.com/embed/X8sIqhzSuXo?si=D7euFmzR5SX1PagL"
        title="YouTube video player" 
        frameborder="0" 
        allow="accelerometer; 
               autoplay; 
               clipboard-write; 
               encrypted-media; 
               gyroscope; 
               picture-in-picture; 
               web-share" 
        allowfullscreen>
</iframe>

### Slides

You can download the lecture slides [here](pdf/cfa_intro.pdf).
