# Assignments {-}

This chapter contains the details and binding information about the two data analysis assignments that comprise the
portfolio upon which your course grade is based.

Below, you can find a brief idea of what each assignment will cover.

- For each assignment, you will use R to analyze some real-world data, and you will write up your results in a concise
report (not a full research paper).
   - Guidelines for these analyses/reports are delineated in the following two sections.
   - You will submit your reports via Brightspace.
- You will complete Assignment 1 in the *Assignment Group* that you join on Brightspace.
- You will complete the second assignment individually.
- The first assignment is graded as pass/fail.
   - You must pass this first assignment to pass the course.
- Your grade on the second assignment constitutes your numeric course grade.

```{r, echo = FALSE, message = FALSE, warning = FALSE, error = TRUE, results = "asis"}
knit_child(here::here("sections", "assignments", "a1.Rmd"),         quiet = TRUE) |> cat(sep = "\n")
knit_child(here::here("sections", "assignments", "a2.Rmd"),         quiet = TRUE) |> cat(sep = "\n")
knit_child(here::here("sections", "assignments", "tips.Rmd"),       quiet = TRUE) |> cat(sep = "\n")
knit_child(here::here("sections", "assignments", "data.Rmd"),       quiet = TRUE) |> cat(sep = "\n")
knit_child(here::here("sections", "assignments", "procedures.Rmd"), quiet = TRUE) |> cat(sep = "\n")
knit_child(here::here("sections", "assignments", "grading.Rmd"),    quiet = TRUE) |> cat(sep = "\n")
knit_child(here::here("sections", "assignments", "rules.Rmd"),      quiet = TRUE) |> cat(sep = "\n")
```

<!--------------------------------------------------------------------------------------------------------------------->

[a1]: https://uu.brightspace.com/d2l/le/lessons/43049/topics/338900
[a2]: https://uu.brightspace.com/d2l/le/lessons/43049/topics/338905
<!-- [groups]: https://uu.blackboard.com/webapps/bb-group-mgmt-LEARN/execute/groupContentList?course_id=_154060_1&action=list&mode=view# -->
[covid_data]: https://surfdrive.surf.nl/files/index.php/s/UAtnDoYbvmtzhm5/download
[covid_reg]: https://surfdrive.surf.nl/files/index.php/s/JCwYJUVz1nH1mT0/download
[covid_codebook]: https://surfdrive.surf.nl/files/index.php/s/24i2Aq0tosKsFeq/download
[fem_data]: https://www.kaggle.com/datasets/lucasgreenwell/feminist-perspectives-scale-responses
[fem_paper]: https://doi.org/10.1111/j.1471-6402.1998.tb00158.x
[hsns_dd_data]: https://www.kaggle.com/datasets/lucasgreenwell/hypersensitive-narcissism-scale
[hsns_paper]: https://doi.org/10.1006/jrpe.1997.2204
[dd_paper]: https://dx.doi.org/10.1037/a0019265
[kims_data]: https://www.kaggle.com/datasets/lucasgreenwell/kentucky-inventory-of-mindfulness-skills-responses
[kims_paper]: https://doi.org/10.1177/1073191104268029
[dass_data]: https://www.kaggle.com/datasets/lucasgreenwell/depression-anxiety-stress-scales-responses
[dass_info]: https://www2.psy.unsw.edu.au/dass/
[pwe_data]: https://www.kaggle.com/datasets/lucasgreenwell/protestant-work-ethic-scale-responses
[nomophobia_data]: https://zenodo.org/record/8209987
[rwa_data]: https://data.mendeley.com/datasets/k9pvh7rc9n/5
[rwa_paper]: https://www.sciencedirect.com/science/article/pii/S2352340922005996
[knitr]: https://yihui.org/knitr/
