%%% Title:    ISEM: Model Comparison
%%% Author:   Kyle M. Lang
%%% Created:  2016-XX-XX
%%% Modified: 2025-10-08

\documentclass[10pt]{beamer}
\usetheme{Utrecht}

\usepackage{graphicx}
\usepackage[natbibapa]{apacite}
\usepackage[libertine]{newtxmath}
\usepackage{fancybox}
\usepackage{booktabs}
\usepackage{relsize}

\newcommand{\eqit}[1]{\textrm{\textit{#1}}}
\newcommand{\pkg}[1]{\textbf{#1}}
\newcommand{\src}[1]{\texttt{#1}}
\newcommand{\rmsc}[1]{\textrm{\textsc{#1}}}

\title{Model Comparison}
\subtitle{Introduction to Statistical Modeling}
\author{Kyle M. Lang}
\institute{Department of Methodology \& Statistics\\Utrecht University}
\date{}

\begin{document}

<<setup, include = FALSE, cache = FALSE>>=
set.seed(235711)

library(knitr)
library(ggplot2)
library(MASS)
library(DAAG)
library(xtable)
library(MLmetrics)
library(dplyr)
library(mvtnorm)
library(lavaan)

source(here::here("code", "supportFunctions.R"))

options(width = 80)
opts_chunk$set(size = "footnotesize",
               fig.align = "center",
               fig.path = "figure/model_comparison-",
               message = FALSE,
               comment = "")
knit_theme$set('edit-kwrite')
@

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[t,plain]
  \titlepage
\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Outline}
  \tableofcontents
\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\sectionslide{Model Comparison}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Nested Models}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Comparing Nested Models}


\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Likelihood Ratio Tests}


\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Wald Tests}


\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Score Tests}


\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Non-Nested Models}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Comparing Non-Nested Models}


\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Information Criteria}


\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\end{document}
