## Rules {-}

------------------------------------------------------------------------------------------------------------------------

### Resources {-}

For both assignments, you may use any reference materials you like, including:

- All course materials
- The course GitBook
- Additional books and papers
- The internet

### Collaboration {-}

You will complete the first assignment in groups.

- Although you will work in groups, your group may not work together with other groups.

You will complete the final assignment individually. 

- For this assignment, you may not work with anyone else.

For both assignments, you are obligated to submit original work (i.e., work conducted for this course by you or your
group). 

- Submitting an assignment that violates this condition constitutes fraud.
- Such cases of fraud will be addressed according to the 
[University's standard policy](https://students.uu.nl/en/practical-information/policies-and-procedures/fraud-and-plagiarism).

------------------------------------------------------------------------------------------------------------------------

### Academic integrity {-}

Hopefully, you also feel a moral obligation to obey the rules. For this course, we have implemented an examination that
allows you to showcase what you have learned in a more realistic way than a written exam would allow. 

- This assessment format spares you the stress of long exams (the two exams for this course used to be 4 hours each) and
the attendant studying/cramming. 
- The assignments will also help you assess your ability to independently analyse data, which is important to know for
your future courses and/or career.

However, this format also assumes that you complete the assignments in good faith. So, I simply ask that you hold up
your end of the bargain, and submit your original work to show us what you’ve learned.

------------------------------------------------------------------------------------------------------------------------

### Using AI tools {-}

You are free to use AI tools like OpenAI’s ChatGPT or GitHub CoPilot, but you must cite the tools you used in the same
way that you would cite any other software. As with citing any other source, properly citing AI tools both attributes
the appropriate credit to the tool’s developers and helps you clearly and accurately describe your own work. In addition
to providing a valid citation, you must also explain how you used the AI tool. Specifically, did you use AI to:

1. Create new content (e.g., use ChatGPT to draft some parts of the text)
1. Modify content that you created (e.g., use CoPilot to debug your R code)

A convenient way to satisfy these requirements would be to provide the necessary information in a short section at the
end of your report. You can think of this section as being analogous to the Conflict of Interest statements you often
see in journal articles.

#### AI tools & academic integrity {-}

Generative AI may be shiny new tech, but that just means AI is like the newest, shiniest gizmo in a toolbox full of
time-tested options, not some paradigm shift in carpentry that deprecates the hammer. The normal ethics of scientific
communication still apply:

1. Transparently describe your work
1. Honestly attribute credit/blame

Of course, the natural corollary of the above is that all the standard penalties for bad behavior also apply.
Obfuscating your use of AI tools or attempting to claim AI-generated content as your own work is a form of academic
fraud that is more-or-less equivalent to plagiarism. We will treat any such attempted subterfuge as academic dishonesty.

Finally, don’t trust The Robots too much! You are ultimately responsible for the work you submit. So, you will have to
own any “mistakes” that wily AI models induce in your work.

------------------------------------------------------------------------------------------------------------------------

### Strict stuff {-}

By submitting your assignments (both group and individual), you confirm the following:

1. You have completed the assignment yourself (or with your group)
1. You are submitting work that you have written yourself (or with your group)
1. You are using your own UU credentials to submit the assignment
1. You have not had outside help that violates the conditions delineated above while completing the assignment

All assignments will be submitted via Ouriginal in Blackboard and, thereby, checked for plagiarism. If fraud or
plagiarism is detected or suspected, we will inform the Board of Examiners in the usual manner. In the event of
demonstrable fraud, the sanctions delineated in Article 5.15 of the
[Education and Examination Regulations (EER)](https://students.uu.nl/en/fss/education-and-examination-regulations-eer)
will apply. 
