<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.3 At-Home Exercises | Introduction to Structural Equation Modeling</title>
  <meta name="description" content="4.3 At-Home Exercises | Introduction to Structural Equation Modeling" />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="4.3 At-Home Exercises | Introduction to Structural Equation Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.3 At-Home Exercises | Introduction to Structural Equation Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="reading-3.html"/>
<link rel="next" href="in-class-exercises-3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="assets/html/style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">Introduction to SEM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a>
<ul>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#reading-questions"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html"><i class="fa fa-check"></i>Logistics</a>
<ul>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#weekly-preparation"><i class="fa fa-check"></i>Weekly preparation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#evaluation"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#attendance"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html"><i class="fa fa-check"></i>Using GenAI</a>
<ul>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#ai-index"><i class="fa fa-check"></i>AI index</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#acceptable-usage-in-this-course"><i class="fa fa-check"></i>Acceptable usage in this course</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#including-ai-generated-content-in-your-work"><i class="fa fa-check"></i>Including AI-generated content in your work</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#referencing-and-academic-integrity"><i class="fa fa-check"></i>Referencing and academic integrity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html#a1_components"><i class="fa fa-check"></i>Required Components</a></li>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html#evaluation-1"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html#submission"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html"><i class="fa fa-check"></i>Assignment 2: Structural Equation Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html#a2_components"><i class="fa fa-check"></i>Required Components</a></li>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html#evaluation-2"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html#submission-1"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#progression"><i class="fa fa-check"></i>Progression</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#reporting_standards"><i class="fa fa-check"></i>Reporting Standards</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html"><i class="fa fa-check"></i>Data</a>
<ul>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#coping-with-covid"><i class="fa fa-check"></i>Coping with Covid</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#feminist-perspectives-scale"><i class="fa fa-check"></i>Feminist Perspectives Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#hypersensitive-narcissism-scale-dirty-dozen"><i class="fa fa-check"></i>Hypersensitive Narcissism Scale &amp; Dirty Dozen</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#kentucky-inventory-of-mindfulness-skills"><i class="fa fa-check"></i>Kentucky Inventory of Mindfulness Skills</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#depression-anxiety-stress-scale"><i class="fa fa-check"></i>Depression Anxiety Stress Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#nomophobia"><i class="fa fa-check"></i>Nomophobia</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#recycled-water-acceptance"><i class="fa fa-check"></i>Recycled Water Acceptance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#group-assignments"><i class="fa fa-check"></i>Group Assignments</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#individual-assignment"><i class="fa fa-check"></i>Individual Assignment</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#resits"><i class="fa fa-check"></i>Resits</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#example-assignment"><i class="fa fa-check"></i>Example Assignment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html"><i class="fa fa-check"></i>Rules</a>
<ul>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#resources-1"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#collaboration"><i class="fa fa-check"></i>Collaboration</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#academic-integrity"><i class="fa fa-check"></i>Academic integrity</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#genai-disclosure-statement"><i class="fa fa-check"></i>GenAI disclosure statement</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#strict-stuff"><i class="fa fa-check"></i>Strict stuff</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
<li class="chapter" data-level="2.1.3" data-path="lecture-1.html"><a href="lecture-1.html#materials-from-the-lecture-meeting"><i class="fa fa-check"></i><b>2.1.3</b> Materials from the lecture meeting</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#answers"><i class="fa fa-check"></i>Answers</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#setup"><i class="fa fa-check"></i><b>2.3.1</b> Setup</a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
<li class="chapter" data-level="2.3.7" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.7</b> </a></li>
<li class="chapter" data-level="2.3.8" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-2"><i class="fa fa-check"></i><b>2.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#setup-1"><i class="fa fa-check"></i><b>2.4.1</b> Setup</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.2</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.3</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.4</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#answers-1"><i class="fa fa-check"></i>Answers</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#answers-2"><i class="fa fa-check"></i>Answers</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#setup-2"><i class="fa fa-check"></i><b>3.3.1</b> Setup</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.2</b> Mediation</a></li>
<li class="chapter" data-level="3.3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.3</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#setup-3"><i class="fa fa-check"></i><b>3.4.1</b> Setup</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.2</b> Mediation</a></li>
<li class="chapter" data-level="3.4.3" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.3</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="cfa-i.html"><a href="cfa-i.html"><i class="fa fa-check"></i><b>4</b> CFA I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recordings-3"><i class="fa fa-check"></i><b>4.1.1</b> Recordings</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#setup-4"><i class="fa fa-check"></i><b>4.3.1</b> Setup</a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#df"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax1"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax2"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
<li class="chapter" data-level="4.3.11" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation2"><i class="fa fa-check"></i><b>4.3.11</b> </a></li>
<li class="chapter" data-level="4.3.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.12</b> </a></li>
<li class="chapter" data-level="4.3.13" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.3.13</b> </a></li>
<li class="chapter" data-level="4.3.14" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.3.14</b> </a></li>
<li class="chapter" data-level="4.3.15" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation3"><i class="fa fa-check"></i><b>4.3.15</b> </a></li>
<li class="chapter" data-level="4.3.16" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.3.16</b> </a></li>
<li class="chapter" data-level="4.3.17" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.3.17</b> </a></li>
<li class="chapter" data-level="4.3.18" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.3.18</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa-ii.html"><a href="cfa-ii.html"><i class="fa fa-check"></i><b>5</b> CFA II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fall-break.html"><a href="fall-break.html"><i class="fa fa-check"></i><b>6</b> Fall Break</a></li>
<li class="chapter" data-level="7" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>7</b> Full SEM</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a></li>
<li class="chapter" data-level="7.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>8</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>8.1</b> Lecture</a></li>
<li class="chapter" data-level="8.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>8.2</b> Reading</a></li>
<li class="chapter" data-level="8.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>8.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="8.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>8.4</b> In-Class Exercises</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Structural Equation Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="at-home-exercises-3" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> At-Home Exercises<a href="at-home-exercises-3.html#at-home-exercises-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This week, we will take our first steps into the world of factor analysis. We’ll begin by fitting some CFA models using
personality scale data.</p>
<hr />
<div id="setup-4" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Setup<a href="at-home-exercises-3.html#setup-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Data:</strong></p>
<p>You will use the following dataset for these exercises.</p>
<ul>
<li><a href="https://surfdrive.surf.nl/files/index.php/s/1hLlshF9xF0rpJH">cattell</a></li>
<li>You can find a codebook for the dataset <a href="data/16PF/codebook.html">here</a></li>
</ul>
<p>This dataset contains 1000 observations of 16X personality items collected as part of the
<a href="https://ipip.ori.org/">International Personality Item Pool</a>. These items are meant to assess Raymond Cattell’s 16 personality factors
(16PF):</p>
<ul>
<li>Warmth</li>
<li>Reasoning</li>
<li>Emotional Stability</li>
<li>Dominance</li>
<li>Liveliness</li>
<li>Rule-Consciousness</li>
<li>Social Boldness</li>
<li>Sensitivity</li>
<li>Vigilance</li>
<li>Abstractness</li>
<li>Privateness</li>
<li>Apprehension</li>
<li>Openness to Change</li>
<li>Self-Reliance</li>
<li>Perfectionism</li>
<li>Tension</li>
</ul>
<p>The <a href="https://en.wikipedia.org/wiki/16PF_Questionnaire">16PF Wikipedia page</a> provides a nice summary of the scale.</p>
<p><strong>Packages:</strong></p>
<p>To complete these exercises, you will need to install the package described below.</p>
<table>
<thead>
<tr class="header">
<th align="left">Package</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">semPlot</td>
<td align="left">Programmatically draw path diagrams in R</td>
</tr>
</tbody>
</table>
<p>Use the <code>install.packages()</code> function to install this package.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="at-home-exercises-3.html#cb124-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;semPlot&quot;</span>, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-45" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> </h3>
<p>Load the <em>cattell</em> data.</p>
<ul>
<li>The relevant data are contained in the [<em>canttell.rds</em>][cattell_data] file.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="at-home-exercises-3.html#cb125-1" tabindex="-1"></a>dataDir <span class="ot">&lt;-</span> <span class="st">&quot;data&quot;</span></span>
<span id="cb125-2"><a href="at-home-exercises-3.html#cb125-2" tabindex="-1"></a>cattell <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(dataDir, <span class="st">&quot;cattell.rds&quot;</span>))</span></code></pre></div>
</details>
<hr />
<p>We’ll first estimate a simple one-dimensional CFA of the <em>Warmth</em> factor. Our target model is defined as follows:</p>
<ul>
<li>One reflective latent factor representing the <em>Warmth</em> dimension</li>
<li>10 observed indicators: {<code>A1</code>, <code>A2</code>, …, <code>A10</code>}</li>
<li>10 residual variances but no residual covariances</li>
</ul>
<p>Basically, our CFA should estimate the default measurement model through which one latent factor generates 10 observed
indicator variables.</p>
<hr />
</div>
<div id="section-46" class="section level3" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> </h3>
<p>Sketch a path diagram of the CFA model described above.</p>
<ul>
<li>Use pencil and paper (or the equivalent); don’t generate the diagram programmatically.</li>
</ul>
<hr />
</div>
<div id="df" class="section level3" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> </h3>
<p>Calculate the following quantities for the <em>Warmth</em> CFA described above.</p>
<ol style="list-style-type: decimal">
<li>The number of parameters in the model.</li>
<li>The pieces of unique information provided by the data.</li>
<li>The number of estimated parameters after applying the necessary scaling constraints.</li>
<li>The degrees of freedom for the estimated model.</li>
</ol>
<details>
<summary>
Click to show the answer
</summary>
<ol style="list-style-type: decimal">
<li>The model contains 21 parameters
<ul>
<li>10 factor loadings</li>
<li>10 residual variances</li>
<li>One latent variance</li>
</ul></li>
<li>Our model will include 10 observed variables, so the data provide 10 (10 + 1) / 2 = 55 pieces of information.</li>
<li>To identify the covariance structure model, we need to fix one parameter. So, we will estimate 20 parameters.</li>
<li>The estimated model will have 55 - 20 = 35 degrees of freedom.</li>
</ol>
</details>
<hr />
</div>
<div id="cfaSyntax1" class="section level3" number="4.3.5">
<h3><span class="header-section-number">4.3.5</span> </h3>
<p>Define the <code>lavaan</code> model syntax for the unidimensional CFA of <em>Warmth</em> described above.</p>
<ul>
<li>Do not specify any mean structure.</li>
<li>Save this model syntax as an object in your environment.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="at-home-exercises-3.html#cb126-1" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb126-2"><a href="at-home-exercises-3.html#cb126-2" tabindex="-1"></a><span class="st">warmth =~ A1 + A2 + A3 + A4 + A5 + A6 + A7 + A8 + A9 + A10</span></span>
<span id="cb126-3"><a href="at-home-exercises-3.html#cb126-3" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
<details>
<summary>
Click for explanation
</summary>
<p>At this point, we only need to define the factor loading map. We can specify all the other options when we estimate the
model.</p>
</details>
</details>
<hr />
</div>
<div id="section-47" class="section level3" number="4.3.6">
<h3><span class="header-section-number">4.3.6</span> </h3>
<p>Estimate the CFA model you defined in <a href="at-home-exercises-3.html#cfaSyntax1">4.3.5</a>, and summarize the results.</p>
<ul>
<li>Use the <code>lavaan::cfa()</code> function to estimate the model.</li>
<li>Use the default settings for the <code>cfa()</code> function.</li>
</ul>
<p>Check the results, and answer the following questions:</p>
<ul>
<li>What is the estimated variance of the <em>Warmth</em> factor?</li>
<li>How is the model identified when using the default settings?</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="at-home-exercises-3.html#cb127-1" tabindex="-1"></a><span class="do">## Load the lavaan package:</span></span>
<span id="cb127-2"><a href="at-home-exercises-3.html#cb127-2" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb127-3"><a href="at-home-exercises-3.html#cb127-3" tabindex="-1"></a></span>
<span id="cb127-4"><a href="at-home-exercises-3.html#cb127-4" tabindex="-1"></a><span class="do">## Estimate the CFA model:</span></span>
<span id="cb127-5"><a href="at-home-exercises-3.html#cb127-5" tabindex="-1"></a>out1<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod1, <span class="at">data =</span> cattell)</span>
<span id="cb127-6"><a href="at-home-exercises-3.html#cb127-6" tabindex="-1"></a></span>
<span id="cb127-7"><a href="at-home-exercises-3.html#cb127-7" tabindex="-1"></a><span class="do">## Summarize the fitted model:</span></span>
<span id="cb127-8"><a href="at-home-exercises-3.html#cb127-8" tabindex="-1"></a><span class="fu">summary</span>(out1<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 21 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        20
## 
##                                                   Used       Total
##   Number of observations                           953        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                               285.889
##   Degrees of freedom                                35
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                1.000                           
##     A2                0.865    0.046   18.909    0.000
##     A3                0.770    0.048   15.888    0.000
##     A4                0.818    0.046   17.622    0.000
##     A5                0.902    0.045   19.872    0.000
##     A6                0.793    0.043   18.354    0.000
##     A7                0.769    0.043   17.715    0.000
##     A8               -0.516    0.052   -9.888    0.000
##     A9               -0.824    0.046  -17.811    0.000
##     A10              -0.466    0.050   -9.413    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.546    0.030   18.365    0.000
##    .A2                0.481    0.025   18.895    0.000
##    .A3                0.694    0.034   20.223    0.000
##    .A4                0.560    0.029   19.575    0.000
##    .A5                0.424    0.023   18.206    0.000
##    .A6                0.454    0.024   19.216    0.000
##    .A7                0.485    0.025   19.533    0.000
##    .A8                1.063    0.050   21.359    0.000
##    .A9                0.547    0.028   19.488    0.000
##    .A10               0.970    0.045   21.409    0.000
##     warmth            0.545    0.046   11.808    0.000</code></pre>
<details>
<summary>
Click for explanation
</summary>
<p>The estimated latent variance is <span class="math inline">\(\psi_{11} = 0.545\)</span>.</p>
<p>The <code>cfa()</code> function is just a wrapper for the <code>lavaan()</code> function with several options set at the defaults you would
want for a standard CFA.</p>
<ul>
<li>By default, the model is identified by fixing the first factor loading of each factor to 1 (due to the argument
<code>auto.fix.first = TRUE</code>).</li>
</ul>
<p>To see a full list of the (many) options you can specify to tweak the behavior of <code>lavaan</code> estimation functions run
<code>?lavOptions</code>.</p>
</details>
</details>
<hr />
</div>
<div id="section-48" class="section level3" number="4.3.7">
<h3><span class="header-section-number">4.3.7</span> </h3>
<p>Do the number of model parameters and degrees of freedom reported in the lavaan output agree with the values you
calculated in <a href="at-home-exercises-3.html#df">4.3.4</a>?</p>
<details>
<summary>
Click to show answer
</summary>
<p>Yes, the values should agree. This first part of the lavaan model summary reports the number of model parameters and the
degrees of freedom.</p>
<pre><code>## lavaan 0.6-19 ended normally after 21 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        20
## 
##                                                   Used       Total
##   Number of observations                           953        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                               285.889
##   Degrees of freedom                                35
##   P-value (Chi-square)                           0.000</code></pre>
<p>In this case, we see that we’ve estimated 20 parameters and we have df = 35.</p>
</details>
<hr />
</div>
<div id="section-49" class="section level3" number="4.3.8">
<h3><span class="header-section-number">4.3.8</span> </h3>
<p>Use the <code>semPaths()</code> function from the <strong>semPlot</strong> package to draw a path diagram of your estimated CFA.</p>
<ul>
<li>Include the parameter estimates in the diagram.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="at-home-exercises-3.html#cb130-1" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb130-2"><a href="at-home-exercises-3.html#cb130-2" tabindex="-1"></a><span class="fu">semPaths</span>(out1<span class="fl">.1</span>, <span class="at">whatLabels =</span> <span class="st">&quot;estimates&quot;</span>)</span></code></pre></div>
<img src="isem_files/figure-html/unnamed-chunk-270-1.png" width="672" />
</details>
<hr />
<p>Now, we’re going to complicate matters slightly by adding another dimension to our model. We’ll now estimate a
two-dimensional CFA that contains correlated <em>Warmth</em> and <em>Dominance</em> factors.</p>
<p>Defined this new model as follows:</p>
<ul>
<li>Two correlated, reflective latent factors: one <em>Warmth</em> factor and one <em>Dominance</em> factor</li>
<li>10 observed indicators of <em>Warmth</em>: {<code>A1</code>, <code>A2</code>, …, <code>A10</code>}</li>
<li>10 observed indicators of <em>Dominance</em>: {<code>D1</code>, <code>D2</code>, …, <code>D10</code>}</li>
<li>No cross-loadings</li>
<li>No residual correlations</li>
</ul>
<p>Again, this CFA should estimate the default measurement model though which two correlated latent factors generate a set
of 20 observed indicators.</p>
<hr />
</div>
<div id="section-50" class="section level3" number="4.3.9">
<h3><span class="header-section-number">4.3.9</span> </h3>
<p>Sketch a path diagram of the CFA model described above.</p>
<ul>
<li>Use pencil and paper (or the equivalent); don’t generate the diagram programmatically.</li>
</ul>
<hr />
</div>
<div id="cfaSyntax2" class="section level3" number="4.3.10">
<h3><span class="header-section-number">4.3.10</span> </h3>
<p>Define the <code>lavaan</code> model syntax for a two-factor model of the <em>Warmth</em> and <em>Dominance</em> items.</p>
<ul>
<li>Save this syntax as an object in your environment.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="at-home-exercises-3.html#cb131-1" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb131-2"><a href="at-home-exercises-3.html#cb131-2" tabindex="-1"></a><span class="st">warmth    =~ A1 + A2 + A3 + A4 + A5 + A6 + A7 + A8 + A9 + A10</span></span>
<span id="cb131-3"><a href="at-home-exercises-3.html#cb131-3" tabindex="-1"></a><span class="st">dominance =~ D1 + D2 + D3 + D4 + D5 + D6 + D7 + D8 + D9 + D10</span></span>
<span id="cb131-4"><a href="at-home-exercises-3.html#cb131-4" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="cfaEstimation2" class="section level3" number="4.3.11">
<h3><span class="header-section-number">4.3.11</span> </h3>
<p>Estimate the two-factor model you specified in <a href="at-home-exercises-3.html#cfaSyntax2">4.3.10</a>, and summarize the results.</p>
<ul>
<li>Identify the model by fixing the first factor loading of each construct to 1.</li>
<li>Do not estimate any mean structure.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="at-home-exercises-3.html#cb132-1" tabindex="-1"></a><span class="do">## Estimate the one factor model:</span></span>
<span id="cb132-2"><a href="at-home-exercises-3.html#cb132-2" tabindex="-1"></a>out2<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod2, <span class="at">data =</span> cattell)</span>
<span id="cb132-3"><a href="at-home-exercises-3.html#cb132-3" tabindex="-1"></a></span>
<span id="cb132-4"><a href="at-home-exercises-3.html#cb132-4" tabindex="-1"></a><span class="do">## Summarize the results:</span></span>
<span id="cb132-5"><a href="at-home-exercises-3.html#cb132-5" tabindex="-1"></a><span class="fu">summary</span>(out2<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 25 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        41
## 
##                                                   Used       Total
##   Number of observations                           932        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                               823.377
##   Degrees of freedom                               169
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                1.000                           
##     A2                0.867    0.046   18.784    0.000
##     A3                0.772    0.049   15.651    0.000
##     A4                0.813    0.047   17.324    0.000
##     A5                0.905    0.046   19.694    0.000
##     A6                0.794    0.044   18.127    0.000
##     A7                0.768    0.044   17.396    0.000
##     A8               -0.531    0.053  -10.033    0.000
##     A9               -0.822    0.047  -17.566    0.000
##     A10              -0.476    0.050   -9.458    0.000
##   dominance =~                                        
##     D1                1.000                           
##     D2                0.844    0.042   20.132    0.000
##     D3                0.506    0.041   12.294    0.000
##     D4                0.526    0.041   12.783    0.000
##     D5                0.771    0.033   23.080    0.000
##     D6                0.467    0.035   13.265    0.000
##     D7               -0.901    0.040  -22.500    0.000
##     D8               -0.409    0.038  -10.843    0.000
##     D9               -0.655    0.040  -16.557    0.000
##     D10              -0.657    0.046  -14.336    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     dominance         0.135    0.024    5.551    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.550    0.030   18.231    0.000
##    .A2                0.470    0.025   18.639    0.000
##    .A3                0.701    0.035   20.026    0.000
##    .A4                0.559    0.029   19.413    0.000
##    .A5                0.418    0.023   17.972    0.000
##    .A6                0.453    0.024   19.023    0.000
##    .A7                0.492    0.025   19.381    0.000
##    .A8                1.053    0.050   21.098    0.000
##    .A9                0.544    0.028   19.303    0.000
##    .A10               0.969    0.046   21.160    0.000
##    .D1                0.327    0.023   14.501    0.000
##    .D2                0.684    0.036   19.186    0.000
##    .D3                0.846    0.040   20.898    0.000
##    .D4                0.838    0.040   20.834    0.000
##    .D5                0.368    0.021   17.825    0.000
##    .D6                0.605    0.029   20.767    0.000
##    .D7                0.549    0.030   18.154    0.000
##    .D8                0.730    0.035   21.066    0.000
##    .D9                0.699    0.035   20.183    0.000
##    .D10               1.002    0.049   20.602    0.000
##     warmth            0.543    0.047   11.638    0.000
##     dominance         0.695    0.048   14.518    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-51" class="section level3" number="4.3.12">
<h3><span class="header-section-number">4.3.12</span> </h3>
<p>Report the following parameter estimates from the model you estimated in <a href="at-home-exercises-3.html#cfaEstimation2">4.3.11</a>.</p>
<ol style="list-style-type: decimal">
<li>The <code>warmth</code> <span class="math inline">\(\rightarrow\)</span> <code>A3</code> factor loading</li>
<li>The <code>dominance</code> <span class="math inline">\(\rightarrow\)</span> <code>D2</code> factor loading</li>
<li>The latent covariance between <em>warmth</em> and <em>dominance</em></li>
</ol>
<details>
<summary>
Click to show answer
</summary>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\lambda_{3,1} = 0.772\)</span></li>
<li><span class="math inline">\(\lambda_{12,2} = 0.844\)</span></li>
<li><span class="math inline">\(\psi_{2,1} = 0.135\)</span></li>
</ol>
</details>
<hr />
</div>
<div id="section-52" class="section level3" number="4.3.13">
<h3><span class="header-section-number">4.3.13</span> </h3>
<p>Based on the CFA you estimated in <a href="at-home-exercises-3.html#cfaEstimation2">4.3.11</a>, can we infer a significant linear association between <em>Warmth</em>
and <em>Dominance</em>?</p>
<ul>
<li>Use the statistics from your estimated model to justify your conclusion.</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<p>Yes, warmth and dominance are significantly correlated
(<span class="math inline">\(\psi_{2,1} = 0.135\)</span>, <span class="math inline">\(SE = 0.02\)</span>, <span class="math inline">\(z = 5.55\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</p>
</details>
<hr />
</div>
<div id="section-53" class="section level3" number="4.3.14">
<h3><span class="header-section-number">4.3.14</span> </h3>
<p>Use the <code>semPaths()</code> function to draw a path diagram of your estimated CFA.</p>
<ul>
<li>Include the parameter estimates in the diagram.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="at-home-exercises-3.html#cb134-1" tabindex="-1"></a><span class="fu">semPaths</span>(out2<span class="fl">.1</span>, <span class="at">whatLabels =</span> <span class="st">&quot;estimates&quot;</span>)</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-275-1.png" width="672" /></p>
</details>
<hr />
</div>
<div id="cfaEstimation3" class="section level3" number="4.3.15">
<h3><span class="header-section-number">4.3.15</span> </h3>
<p>Estimate a modified version of the two-factor CFA from <a href="at-home-exercises-3.html#cfaEstimation2">4.3.11</a>, and summarize the results.</p>
<ul>
<li>Estimate the mean structure.</li>
<li>Identify the model with the fixed factor method (i.e., standardize the latent variables).</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="at-home-exercises-3.html#cb135-1" tabindex="-1"></a>out2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod2, <span class="at">data =</span> cattell, <span class="at">meanstructure =</span> <span class="cn">TRUE</span>, <span class="at">std.lv =</span> <span class="cn">TRUE</span>)</span>
<span id="cb135-2"><a href="at-home-exercises-3.html#cb135-2" tabindex="-1"></a><span class="fu">summary</span>(out2<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 17 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        61
## 
##                                                   Used       Total
##   Number of observations                           932        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                               823.377
##   Degrees of freedom                               169
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                0.737    0.032   23.276    0.000
##     A2                0.639    0.029   22.266    0.000
##     A3                0.569    0.033   17.483    0.000
##     A4                0.598    0.030   19.926    0.000
##     A5                0.666    0.028   23.856    0.000
##     A6                0.585    0.028   21.184    0.000
##     A7                0.566    0.028   20.037    0.000
##     A8               -0.391    0.037  -10.467    0.000
##     A9               -0.605    0.030  -20.298    0.000
##     A10              -0.350    0.036   -9.819    0.000
##   dominance =~                                        
##     D1                0.834    0.029   29.036    0.000
##     D2                0.703    0.034   20.891    0.000
##     D3                0.422    0.034   12.451    0.000
##     D4                0.439    0.034   12.960    0.000
##     D5                0.643    0.026   24.327    0.000
##     D6                0.389    0.029   13.463    0.000
##     D7               -0.751    0.032  -23.630    0.000
##     D8               -0.341    0.031  -10.950    0.000
##     D9               -0.546    0.032  -16.956    0.000
##     D10              -0.548    0.038  -14.589    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     dominance         0.219    0.036    6.041    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                3.755    0.034  109.685    0.000
##    .A2                3.871    0.031  126.109    0.000
##    .A3                3.844    0.033  115.977    0.000
##    .A4                3.687    0.031  117.542    0.000
##    .A5                3.893    0.030  128.008    0.000
##    .A6                3.761    0.029  128.704    0.000
##    .A7                3.894    0.030  131.943    0.000
##    .A8                2.931    0.036   81.503    0.000
##    .A9                2.135    0.031   68.298    0.000
##    .A10               2.462    0.034   71.941    0.000
##    .D1                3.515    0.033  106.132    0.000
##    .D2                3.343    0.036   94.031    0.000
##    .D3                3.605    0.033  108.744    0.000
##    .D4                3.587    0.033  107.897    0.000
##    .D5                3.694    0.029  127.619    0.000
##    .D6                3.615    0.028  126.910    0.000
##    .D7                2.622    0.035   75.893    0.000
##    .D8                2.085    0.030   69.203    0.000
##    .D9                2.855    0.033   87.284    0.000
##    .D10               2.381    0.037   63.692    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.550    0.030   18.231    0.000
##    .A2                0.470    0.025   18.639    0.000
##    .A3                0.701    0.035   20.026    0.000
##    .A4                0.559    0.029   19.413    0.000
##    .A5                0.418    0.023   17.972    0.000
##    .A6                0.453    0.024   19.023    0.000
##    .A7                0.492    0.025   19.381    0.000
##    .A8                1.053    0.050   21.098    0.000
##    .A9                0.544    0.028   19.303    0.000
##    .A10               0.969    0.046   21.160    0.000
##    .D1                0.327    0.023   14.501    0.000
##    .D2                0.684    0.036   19.186    0.000
##    .D3                0.846    0.040   20.898    0.000
##    .D4                0.838    0.040   20.834    0.000
##    .D5                0.368    0.021   17.825    0.000
##    .D6                0.605    0.029   20.767    0.000
##    .D7                0.549    0.030   18.154    0.000
##    .D8                0.730    0.035   21.066    0.000
##    .D9                0.699    0.035   20.183    0.000
##    .D10               1.002    0.049   20.602    0.000
##     warmth            1.000                           
##     dominance         1.000</code></pre>
</details>
<hr />
</div>
<div id="section-54" class="section level3" number="4.3.16">
<h3><span class="header-section-number">4.3.16</span> </h3>
<p>Report the following parameter estimates from the model you estimated in <a href="at-home-exercises-3.html#cfaEstimation3">4.3.15</a>.</p>
<ol style="list-style-type: decimal">
<li>The item intercept for <code>A1</code></li>
<li>The item intercept for <code>D5</code></li>
<li>The mean of the <em>Warmth</em> factor</li>
</ol>
<details>
<summary>
Click to show answer
</summary>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\tau_1 = 3.76\)</span></li>
<li><span class="math inline">\(\tau_{15} = 3.69\)</span></li>
<li>This is a bit of a trick question. We fixed the latent means to zero for model identification, so we don’t have an
estimated latent mean for the warmth factor.</li>
</ol>
</details>
<hr />
</div>
<div id="section-55" class="section level3" number="4.3.17">
<h3><span class="header-section-number">4.3.17</span> </h3>
<p>Based on the CFA you estimated in <a href="at-home-exercises-3.html#cfaEstimation3">4.3.15</a>, how strong is the association between <em>Warmth</em> and <em>Dominance</em>?</p>
<ul>
<li>Use the statistics from your estimated model to justify your conclusion.</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<p>We set the scale by standardizing the latent factors, so we can interpret the latent covariance as a correlation. Hence,
the estimated latent covariance of <span class="math inline">\(\psi_{2,1} = 0.219\)</span> suggests a weak linear association between <em>Warmth</em> and
<em>Dominance</em>.</p>
</details>
<hr />
</div>
<div id="section-56" class="section level3" number="4.3.18">
<h3><span class="header-section-number">4.3.18</span> </h3>
<p>Use the <code>semPaths()</code> function to draw a path diagram of the CFA you estimated in <a href="at-home-exercises-3.html#cfaEstimation3">4.3.15</a>.</p>
<ul>
<li>Include the parameter estimates in the diagram.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="at-home-exercises-3.html#cb137-1" tabindex="-1"></a><span class="fu">semPaths</span>(out2<span class="fl">.2</span>, <span class="at">whatLabels =</span> <span class="st">&quot;estimates&quot;</span>)</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-279-1.png" width="672" /></p>
</details>
<hr />
<p>End of At-Home Exercises</p>
<hr />
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reading-3.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="in-class-exercises-3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "search": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
