<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.4 In-Class Exercises | Introduction to Structural Equation Modeling</title>
  <meta name="description" content="4.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="4.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.4 In-Class Exercises | Introduction to Structural Equation Modeling" />
  
  
  

<meta name="author" content="Kyle M. Lang" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="at-home-exercises-3.html"/>
<link rel="next" href="cfa-ii.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="assets/html/style.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">Introduction to SEM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="acknowledgement.html"><a href="acknowledgement.html"><i class="fa fa-check"></i>Acknowledgement</a></li>
<li class="chapter" data-level="" data-path="instructors.html"><a href="instructors.html"><i class="fa fa-check"></i>Instructors</a></li>
<li class="chapter" data-level="" data-path="course-overview.html"><a href="course-overview.html"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html"><i class="fa fa-check"></i>Learning goals</a>
<ul>
<li class="chapter" data-level="" data-path="learning-goals.html"><a href="learning-goals.html#background"><i class="fa fa-check"></i>Background knowledge</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a>
<ul>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#literature"><i class="fa fa-check"></i>Literature</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#reading-questions"><i class="fa fa-check"></i>Reading questions</a></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html#software"><i class="fa fa-check"></i>Software</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html"><i class="fa fa-check"></i>Logistics</a>
<ul>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#weekly-preparation"><i class="fa fa-check"></i>Weekly preparation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#evaluation"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="logistics.html"><a href="logistics.html#attendance"><i class="fa fa-check"></i>Attendance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html"><i class="fa fa-check"></i>Using GenAI</a>
<ul>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#ai-index"><i class="fa fa-check"></i>AI index</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#acceptable-usage-in-this-course"><i class="fa fa-check"></i>Acceptable usage in this course</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#including-ai-generated-content-in-your-work"><i class="fa fa-check"></i>Including AI-generated content in your work</a></li>
<li class="chapter" data-level="" data-path="ai_policy.html"><a href="ai_policy.html#referencing-and-academic-integrity"><i class="fa fa-check"></i>Referencing and academic integrity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html"><i class="fa fa-check"></i>Assignment 1: Path Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html#a1_components"><i class="fa fa-check"></i>Required Components</a></li>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html#evaluation-1"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a1.html"><a href="a1.html#submission"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html"><i class="fa fa-check"></i>Assignment 2: Structural Equation Modeling</a>
<ul>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html#a2_components"><i class="fa fa-check"></i>Required Components</a></li>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html#evaluation-2"><i class="fa fa-check"></i>Evaluation</a></li>
<li class="chapter" data-level="" data-path="a2.html"><a href="a2.html#submission-1"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html"><i class="fa fa-check"></i>Elaboration &amp; Tips</a>
<ul>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#progression"><i class="fa fa-check"></i>Progression</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#rq"><i class="fa fa-check"></i>Theoretical Model &amp; Research Question</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#model_assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="elaboration-tips.html"><a href="elaboration-tips.html#reporting_standards"><i class="fa fa-check"></i>Reporting Standards</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html"><i class="fa fa-check"></i>Data</a>
<ul>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#coping-with-covid"><i class="fa fa-check"></i>Coping with Covid</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#feminist-perspectives-scale"><i class="fa fa-check"></i>Feminist Perspectives Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#hypersensitive-narcissism-scale-dirty-dozen"><i class="fa fa-check"></i>Hypersensitive Narcissism Scale &amp; Dirty Dozen</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#kentucky-inventory-of-mindfulness-skills"><i class="fa fa-check"></i>Kentucky Inventory of Mindfulness Skills</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#depression-anxiety-stress-scale"><i class="fa fa-check"></i>Depression Anxiety Stress Scale</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#nomophobia"><i class="fa fa-check"></i>Nomophobia</a></li>
<li class="chapter" data-level="" data-path="data_options.html"><a href="data_options.html#recycled-water-acceptance"><i class="fa fa-check"></i>Recycled Water Acceptance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html"><i class="fa fa-check"></i>Procedures</a>
<ul>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#formatting"><i class="fa fa-check"></i>Formatting</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#length"><i class="fa fa-check"></i>Length</a></li>
<li class="chapter" data-level="" data-path="procedures.html"><a href="procedures.html#submission-2"><i class="fa fa-check"></i>Submission</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html"><i class="fa fa-check"></i>Grading</a>
<ul>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#group-assignments"><i class="fa fa-check"></i>Group Assignments</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#individual-assignment"><i class="fa fa-check"></i>Individual Assignment</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#resits"><i class="fa fa-check"></i>Resits</a></li>
<li class="chapter" data-level="" data-path="grading.html"><a href="grading.html#example-assignment"><i class="fa fa-check"></i>Example Assignment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html"><i class="fa fa-check"></i>Rules</a>
<ul>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#resources-1"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#collaboration"><i class="fa fa-check"></i>Collaboration</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#academic-integrity"><i class="fa fa-check"></i>Academic integrity</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#genai-disclosure-statement"><i class="fa fa-check"></i>GenAI disclosure statement</a></li>
<li class="chapter" data-level="" data-path="rules.html"><a href="rules.html#strict-stuff"><i class="fa fa-check"></i>Strict stuff</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="software-setup.html"><a href="software-setup.html"><i class="fa fa-check"></i>Software Setup</a>
<ul>
<li class="chapter" data-level="" data-path="typographic-conventions.html"><a href="typographic-conventions.html"><i class="fa fa-check"></i>Typographic Conventions</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html"><i class="fa fa-check"></i>Installing software</a>
<ul>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-rstudio"><i class="fa fa-check"></i>Installing RStudio</a></li>
<li class="chapter" data-level="" data-path="installing-software.html"><a href="installing-software.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-data.html"><a href="course-data.html"><i class="fa fa-check"></i>Course Data</a>
<ul>
<li class="chapter" data-level="" data-path="note-on-data-updates.html"><a href="note-on-data-updates.html"><i class="fa fa-check"></i>Note on Data Updates</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lecture.html"><a href="lecture.html"><i class="fa fa-check"></i><b>1.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="lecture.html"><a href="lecture.html#recordings"><i class="fa fa-check"></i><b>1.1.1</b> Recordings</a></li>
<li class="chapter" data-level="1.1.2" data-path="lecture.html"><a href="lecture.html#slides"><i class="fa fa-check"></i><b>1.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>1.2</b> Reading</a></li>
<li class="chapter" data-level="1.3" data-path="at-home-exercises.html"><a href="at-home-exercises.html"><i class="fa fa-check"></i><b>1.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="1.4" data-path="in-class-exercises.html"><a href="in-class-exercises.html"><i class="fa fa-check"></i><b>1.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="" data-path="in-class-exercises.html"><a href="in-class-exercises.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-path-analysis.html"><a href="statistical-modeling-path-analysis.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling &amp; Path Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lecture-1.html"><a href="lecture-1.html"><i class="fa fa-check"></i><b>2.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="lecture-1.html"><a href="lecture-1.html#recordings-1"><i class="fa fa-check"></i><b>2.1.1</b> Recordings</a></li>
<li class="chapter" data-level="2.1.2" data-path="lecture-1.html"><a href="lecture-1.html#slides-1"><i class="fa fa-check"></i><b>2.1.2</b> Slides</a></li>
<li class="chapter" data-level="2.1.3" data-path="lecture-1.html"><a href="lecture-1.html#materials-from-the-lecture-meeting"><i class="fa fa-check"></i><b>2.1.3</b> Materials from the lecture meeting</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="reading-1.html"><a href="reading-1.html"><i class="fa fa-check"></i><b>2.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#reference"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#questions"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#answers"><i class="fa fa-check"></i>Answers</a></li>
<li class="chapter" data-level="" data-path="reading-1.html"><a href="reading-1.html#suggested-reading-optional"><i class="fa fa-check"></i>Suggested Reading (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html"><i class="fa fa-check"></i><b>2.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#setup"><i class="fa fa-check"></i><b>2.3.1</b> Setup</a></li>
<li class="chapter" data-level="2.3.2" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section"><i class="fa fa-check"></i><b>2.3.2</b> </a></li>
<li class="chapter" data-level="2.3.3" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-1"><i class="fa fa-check"></i><b>2.3.3</b> </a></li>
<li class="chapter" data-level="2.3.4" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr1"><i class="fa fa-check"></i><b>2.3.4</b> </a></li>
<li class="chapter" data-level="2.3.5" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr2"><i class="fa fa-check"></i><b>2.3.5</b> </a></li>
<li class="chapter" data-level="2.3.6" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#slr3"><i class="fa fa-check"></i><b>2.3.6</b> </a></li>
<li class="chapter" data-level="2.3.7" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#mlr"><i class="fa fa-check"></i><b>2.3.7</b> </a></li>
<li class="chapter" data-level="2.3.8" data-path="at-home-exercises-1.html"><a href="at-home-exercises-1.html#section-2"><i class="fa fa-check"></i><b>2.3.8</b> </a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html"><i class="fa fa-check"></i><b>2.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#setup-1"><i class="fa fa-check"></i><b>2.4.1</b> Setup</a></li>
<li class="chapter" data-level="2.4.2" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#data-exploration"><i class="fa fa-check"></i><b>2.4.2</b> Data Exploration</a></li>
<li class="chapter" data-level="2.4.3" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#linear-modeling"><i class="fa fa-check"></i><b>2.4.3</b> Linear Modeling</a></li>
<li class="chapter" data-level="2.4.4" data-path="in-class-exercises-1.html"><a href="in-class-exercises-1.html#categorical-ivs"><i class="fa fa-check"></i><b>2.4.4</b> Categorical IVs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mediation-moderation.html"><a href="mediation-moderation.html"><i class="fa fa-check"></i><b>3</b> Mediation &amp; Moderation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lecture-2.html"><a href="lecture-2.html"><i class="fa fa-check"></i><b>3.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="lecture-2.html"><a href="lecture-2.html#recordings-2"><i class="fa fa-check"></i><b>3.1.1</b> Recordings</a></li>
<li class="chapter" data-level="3.1.2" data-path="lecture-2.html"><a href="lecture-2.html#slides-2"><i class="fa fa-check"></i><b>3.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="reading-2.html"><a href="reading-2.html"><i class="fa fa-check"></i><b>3.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-1"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-1"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#answers-1"><i class="fa fa-check"></i>Answers</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#reference-2"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#questions-2"><i class="fa fa-check"></i>Questions</a></li>
<li class="chapter" data-level="" data-path="reading-2.html"><a href="reading-2.html#answers-2"><i class="fa fa-check"></i>Answers</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html"><i class="fa fa-check"></i><b>3.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#setup-2"><i class="fa fa-check"></i><b>3.3.1</b> Setup</a></li>
<li class="chapter" data-level="3.3.2" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#mediation"><i class="fa fa-check"></i><b>3.3.2</b> Mediation</a></li>
<li class="chapter" data-level="3.3.3" data-path="at-home-exercises-2.html"><a href="at-home-exercises-2.html#moderation"><i class="fa fa-check"></i><b>3.3.3</b> Moderation</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html"><i class="fa fa-check"></i><b>3.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#setup-3"><i class="fa fa-check"></i><b>3.4.1</b> Setup</a></li>
<li class="chapter" data-level="3.4.2" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#mediation-1"><i class="fa fa-check"></i><b>3.4.2</b> Mediation</a></li>
<li class="chapter" data-level="3.4.3" data-path="in-class-exercises-2.html"><a href="in-class-exercises-2.html#moderation-1"><i class="fa fa-check"></i><b>3.4.3</b> Moderation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="cfa-i.html"><a href="cfa-i.html"><i class="fa fa-check"></i><b>4</b> CFA I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lecture-3.html"><a href="lecture-3.html"><i class="fa fa-check"></i><b>4.1</b> Lecture</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="lecture-3.html"><a href="lecture-3.html#recordings-3"><i class="fa fa-check"></i><b>4.1.1</b> Recordings</a></li>
<li class="chapter" data-level="4.1.2" data-path="lecture-3.html"><a href="lecture-3.html#slides-3"><i class="fa fa-check"></i><b>4.1.2</b> Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="reading-3.html"><a href="reading-3.html"><i class="fa fa-check"></i><b>4.2</b> Reading</a>
<ul>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#reference-3"><i class="fa fa-check"></i>Reference</a></li>
<li class="chapter" data-level="" data-path="reading-3.html"><a href="reading-3.html#questions-3"><i class="fa fa-check"></i>Questions</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html"><i class="fa fa-check"></i><b>4.3</b> At-Home Exercises</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#setup-4"><i class="fa fa-check"></i><b>4.3.1</b> Setup</a></li>
<li class="chapter" data-level="4.3.2" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-45"><i class="fa fa-check"></i><b>4.3.2</b> </a></li>
<li class="chapter" data-level="4.3.3" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-46"><i class="fa fa-check"></i><b>4.3.3</b> </a></li>
<li class="chapter" data-level="4.3.4" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#df"><i class="fa fa-check"></i><b>4.3.4</b> </a></li>
<li class="chapter" data-level="4.3.5" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax1"><i class="fa fa-check"></i><b>4.3.5</b> </a></li>
<li class="chapter" data-level="4.3.6" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-47"><i class="fa fa-check"></i><b>4.3.6</b> </a></li>
<li class="chapter" data-level="4.3.7" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-48"><i class="fa fa-check"></i><b>4.3.7</b> </a></li>
<li class="chapter" data-level="4.3.8" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-49"><i class="fa fa-check"></i><b>4.3.8</b> </a></li>
<li class="chapter" data-level="4.3.9" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-50"><i class="fa fa-check"></i><b>4.3.9</b> </a></li>
<li class="chapter" data-level="4.3.10" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax2"><i class="fa fa-check"></i><b>4.3.10</b> </a></li>
<li class="chapter" data-level="4.3.11" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation2"><i class="fa fa-check"></i><b>4.3.11</b> </a></li>
<li class="chapter" data-level="4.3.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-51"><i class="fa fa-check"></i><b>4.3.12</b> </a></li>
<li class="chapter" data-level="4.3.13" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-52"><i class="fa fa-check"></i><b>4.3.13</b> </a></li>
<li class="chapter" data-level="4.3.14" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-53"><i class="fa fa-check"></i><b>4.3.14</b> </a></li>
<li class="chapter" data-level="4.3.15" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation3"><i class="fa fa-check"></i><b>4.3.15</b> </a></li>
<li class="chapter" data-level="4.3.16" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-54"><i class="fa fa-check"></i><b>4.3.16</b> </a></li>
<li class="chapter" data-level="4.3.17" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-55"><i class="fa fa-check"></i><b>4.3.17</b> </a></li>
<li class="chapter" data-level="4.3.18" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#section-56"><i class="fa fa-check"></i><b>4.3.18</b> </a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html"><i class="fa fa-check"></i><b>4.4</b> In-Class Exercises</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-57"><i class="fa fa-check"></i><b>4.4.1</b> </a></li>
<li class="chapter" data-level="4.4.2" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#dfClass"><i class="fa fa-check"></i><b>4.4.2</b> </a></li>
<li class="chapter" data-level="4.4.3" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaSyntaxClass1"><i class="fa fa-check"></i><b>4.4.3</b> </a></li>
<li class="chapter" data-level="4.4.4" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#cfaEstimationClass1"><i class="fa fa-check"></i><b>4.4.4</b> </a></li>
<li class="chapter" data-level="4.4.5" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-58"><i class="fa fa-check"></i><b>4.4.5</b> </a></li>
<li class="chapter" data-level="4.4.6" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-59"><i class="fa fa-check"></i><b>4.4.6</b> </a></li>
<li class="chapter" data-level="4.4.7" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-60"><i class="fa fa-check"></i><b>4.4.7</b> </a></li>
<li class="chapter" data-level="4.4.8" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-61"><i class="fa fa-check"></i><b>4.4.8</b> </a></li>
<li class="chapter" data-level="4.4.9" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-62"><i class="fa fa-check"></i><b>4.4.9</b> </a></li>
<li class="chapter" data-level="4.4.10" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-63"><i class="fa fa-check"></i><b>4.4.10</b> </a></li>
<li class="chapter" data-level="4.4.11" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-64"><i class="fa fa-check"></i><b>4.4.11</b> </a></li>
<li class="chapter" data-level="4.4.12" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaSyntax2"><i class="fa fa-check"></i><b>4.4.12</b> </a></li>
<li class="chapter" data-level="4.4.13" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation2"><i class="fa fa-check"></i><b>4.4.13</b> </a></li>
<li class="chapter" data-level="4.4.14" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-65"><i class="fa fa-check"></i><b>4.4.14</b> </a></li>
<li class="chapter" data-level="4.4.15" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-66"><i class="fa fa-check"></i><b>4.4.15</b> </a></li>
<li class="chapter" data-level="4.4.16" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-67"><i class="fa fa-check"></i><b>4.4.16</b> </a></li>
<li class="chapter" data-level="4.4.17" data-path="at-home-exercises-3.html"><a href="at-home-exercises-3.html#cfaEstimation3"><i class="fa fa-check"></i><b>4.4.17</b> </a></li>
<li class="chapter" data-level="4.4.18" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-68"><i class="fa fa-check"></i><b>4.4.18</b> </a></li>
<li class="chapter" data-level="4.4.19" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-69"><i class="fa fa-check"></i><b>4.4.19</b> </a></li>
<li class="chapter" data-level="4.4.20" data-path="in-class-exercises-3.html"><a href="in-class-exercises-3.html#section-70"><i class="fa fa-check"></i><b>4.4.20</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cfa-ii.html"><a href="cfa-ii.html"><i class="fa fa-check"></i><b>5</b> CFA II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lecture-4.html"><a href="lecture-4.html"><i class="fa fa-check"></i><b>5.1</b> Lecture</a></li>
<li class="chapter" data-level="5.2" data-path="reading-4.html"><a href="reading-4.html"><i class="fa fa-check"></i><b>5.2</b> Reading</a></li>
<li class="chapter" data-level="5.3" data-path="at-home-exercises-4.html"><a href="at-home-exercises-4.html"><i class="fa fa-check"></i><b>5.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="5.4" data-path="in-class-exercises-4.html"><a href="in-class-exercises-4.html"><i class="fa fa-check"></i><b>5.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fall-break.html"><a href="fall-break.html"><i class="fa fa-check"></i><b>6</b> Fall Break</a></li>
<li class="chapter" data-level="7" data-path="full-sem.html"><a href="full-sem.html"><i class="fa fa-check"></i><b>7</b> Full SEM</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-5.html"><a href="lecture-5.html"><i class="fa fa-check"></i><b>7.1</b> Lecture</a></li>
<li class="chapter" data-level="7.2" data-path="reading-5.html"><a href="reading-5.html"><i class="fa fa-check"></i><b>7.2</b> Reading</a></li>
<li class="chapter" data-level="7.3" data-path="at-home-exercises-5.html"><a href="at-home-exercises-5.html"><i class="fa fa-check"></i><b>7.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="7.4" data-path="in-class-exercises-5.html"><a href="in-class-exercises-5.html"><i class="fa fa-check"></i><b>7.4</b> In-Class Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multiple-group-models.html"><a href="multiple-group-models.html"><i class="fa fa-check"></i><b>8</b> Multiple Group Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lecture-6.html"><a href="lecture-6.html"><i class="fa fa-check"></i><b>8.1</b> Lecture</a></li>
<li class="chapter" data-level="8.2" data-path="reading-6.html"><a href="reading-6.html"><i class="fa fa-check"></i><b>8.2</b> Reading</a></li>
<li class="chapter" data-level="8.3" data-path="at-home-exercises-6.html"><a href="at-home-exercises-6.html"><i class="fa fa-check"></i><b>8.3</b> At-Home Exercises</a></li>
<li class="chapter" data-level="8.4" data-path="in-class-exercises-6.html"><a href="in-class-exercises-6.html"><i class="fa fa-check"></i><b>8.4</b> In-Class Exercises</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Structural Equation Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="in-class-exercises-3" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> In-Class Exercises<a href="in-class-exercises-3.html#in-class-exercises-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this week’s in-class exercises, we’ll continue modeling the Cattell 16PF items usign CFA. We will use the same
dataset that you analyzed in the at-home exercises.</p>
<ul>
<li><a href="https://surfdrive.surf.nl/files/index.php/s/1hLlshF9xF0rpJH">cattell</a></li>
<li>You can find a codebook for the dataset <a href="data/16PF/codebook.html">here</a></li>
</ul>
<hr />
<div id="section-57" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> </h3>
<p>Load the <em>cattell</em> data.</p>
<ul>
<li>The relevant data are contained in the [<em>canttell.rds</em>][cattell_data] file.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="in-class-exercises-3.html#cb138-1" tabindex="-1"></a>dataDir <span class="ot">&lt;-</span> <span class="st">&quot;data&quot;</span></span>
<span id="cb138-2"><a href="in-class-exercises-3.html#cb138-2" tabindex="-1"></a>cattell <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(dataDir, <span class="st">&quot;cattell.rds&quot;</span>))</span></code></pre></div>
</details>
<hr />
<p>In the following exercises, we’ll work primarily with the four-factor CFA shown in the following path diagram. This CFA
models the measurement of the <em>Warmth</em>, <em>Liveliness</em>, <em>Vigilance</em>, and <em>Tension</em> factors from the 16PF.</p>
<p><img src="assets/images/week4_class_path_diagram.png" /></p>
<hr />
</div>
<div id="dfClass" class="section level3" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> </h3>
<p>Calculate the following quantities for the CFA model shown above.</p>
<ol style="list-style-type: decimal">
<li>The number of parameters in the model.</li>
<li>The pieces of unique information provided by the data.</li>
<li>The number of estimated parameters after applying the necessary scaling constraints.</li>
<li>The degrees of freedom for the estimated model.</li>
</ol>
<details>
<summary>
Click to show the answer
</summary>
<ol style="list-style-type: decimal">
<li>The model contains 88 parameters
<ul>
<li>39 factor loadings</li>
<li>39 residual variances</li>
<li>4 latent variances</li>
<li>6 latent covariances</li>
</ul></li>
<li>Our model will include 39 observed variables, so the data provide 39 (39 + 1) / 2 = 780 pieces of information.</li>
<li>To identify the covariance structure model, we need to fix one parameter in each factor’s submodel. So, we will
estimate 84 parameters.</li>
<li>The estimated model will have 780 - 84 = 696 degrees of freedom.</li>
</ol>
</details>
<hr />
</div>
<div id="cfaSyntaxClass1" class="section level3" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> </h3>
<p>Define the <code>lavaan</code> model syntax for the four-factor CFA shown above above.</p>
<ul>
<li>Do not specify any mean structure.</li>
<li>Save this model syntax as an object in your environment.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="in-class-exercises-3.html#cb139-1" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb139-2"><a href="in-class-exercises-3.html#cb139-2" tabindex="-1"></a><span class="st">warmth     =~ A1 + A2 + A3 + A4 + A5 + A6 + A7 + A8 + A9 + A10</span></span>
<span id="cb139-3"><a href="in-class-exercises-3.html#cb139-3" tabindex="-1"></a><span class="st">liveliness =~ E1 + E2 + E3 + E4 + E5 + E6 + E7 + E8 + E9 + E10</span></span>
<span id="cb139-4"><a href="in-class-exercises-3.html#cb139-4" tabindex="-1"></a><span class="st">vigilance  =~ I1 + I2 + I3 + I4 + I5 + I6 + I7 + I8 + I9 + I10</span></span>
<span id="cb139-5"><a href="in-class-exercises-3.html#cb139-5" tabindex="-1"></a><span class="st">tension    =~ P1 + P2 + P3 + P4 + P5 + P6 + P7 + P8 + P9</span></span>
<span id="cb139-6"><a href="in-class-exercises-3.html#cb139-6" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="cfaEstimationClass1" class="section level3" number="4.4.4">
<h3><span class="header-section-number">4.4.4</span> </h3>
<p>Estimate the CFA model you defined in <a href="in-class-exercises-3.html#cfaSyntaxClass1">4.4.3</a>, and summarize the results.</p>
<ul>
<li>Use the <code>lavaan::cfa()</code> function to estimate the model.</li>
<li>Use the “marker variable method” to set the scale of the latent factors.</li>
<li>Use the default settings for the <code>cfa()</code> function.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="in-class-exercises-3.html#cb140-1" tabindex="-1"></a><span class="do">## Load the lavaan package:</span></span>
<span id="cb140-2"><a href="in-class-exercises-3.html#cb140-2" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb140-3"><a href="in-class-exercises-3.html#cb140-3" tabindex="-1"></a></span>
<span id="cb140-4"><a href="in-class-exercises-3.html#cb140-4" tabindex="-1"></a><span class="do">## Estimate the CFA model:</span></span>
<span id="cb140-5"><a href="in-class-exercises-3.html#cb140-5" tabindex="-1"></a>out1<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod1, <span class="at">data =</span> cattell)</span>
<span id="cb140-6"><a href="in-class-exercises-3.html#cb140-6" tabindex="-1"></a></span>
<span id="cb140-7"><a href="in-class-exercises-3.html#cb140-7" tabindex="-1"></a><span class="do">## Summarize the fitted model:</span></span>
<span id="cb140-8"><a href="in-class-exercises-3.html#cb140-8" tabindex="-1"></a><span class="fu">summary</span>(out1<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 43 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##                                                   Used       Total
##   Number of observations                           894        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              3664.769
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                1.000                           
##     A2                0.907    0.047   19.346    0.000
##     A3                0.749    0.049   15.187    0.000
##     A4                0.820    0.047   17.303    0.000
##     A5                0.914    0.046   19.781    0.000
##     A6                0.811    0.044   18.305    0.000
##     A7                0.760    0.044   17.301    0.000
##     A8               -0.521    0.053   -9.745    0.000
##     A9               -0.824    0.047  -17.396    0.000
##     A10              -0.458    0.051   -9.042    0.000
##   liveliness =~                                       
##     E1                1.000                           
##     E2                1.218    0.054   22.461    0.000
##     E3                0.611    0.044   13.847    0.000
##     E4                1.109    0.053   20.920    0.000
##     E5                0.425    0.035   12.009    0.000
##     E6                0.791    0.051   15.508    0.000
##     E7               -0.292    0.046   -6.351    0.000
##     E8               -0.896    0.053  -17.039    0.000
##     E9               -0.241    0.041   -5.856    0.000
##     E10              -0.538    0.049  -10.950    0.000
##   vigilance =~                                        
##     I1                1.000                           
##     I2                1.196    0.096   12.467    0.000
##     I3                1.019    0.088   11.579    0.000
##     I4                1.592    0.113   14.142    0.000
##     I5                0.900    0.087   10.370    0.000
##     I6                1.108    0.093   11.882    0.000
##     I7               -1.299    0.096  -13.491    0.000
##     I8               -1.471    0.106  -13.864    0.000
##     I9               -1.307    0.096  -13.686    0.000
##     I10              -1.015    0.086  -11.836    0.000
##   tension =~                                          
##     P1                1.000                           
##     P2                0.902    0.038   23.796    0.000
##     P3                0.520    0.039   13.470    0.000
##     P4                0.548    0.037   14.689    0.000
##     P5                0.390    0.034   11.554    0.000
##     P6                0.564    0.038   14.958    0.000
##     P7                0.397    0.040    9.949    0.000
##     P8               -0.764    0.038  -20.222    0.000
##     P9               -0.400    0.037  -10.907    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     liveliness        0.306    0.030   10.185    0.000
##     vigilance        -0.205    0.022   -9.239    0.000
##     tension          -0.277    0.032   -8.696    0.000
##   liveliness ~~                                       
##     vigilance        -0.123    0.020   -6.114    0.000
##     tension          -0.052    0.033   -1.555    0.120
##   vigilance ~~                                        
##     tension           0.299    0.030    9.887    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.554    0.030   18.246    0.000
##    .A2                0.441    0.024   18.145    0.000
##    .A3                0.702    0.035   19.865    0.000
##    .A4                0.554    0.029   19.199    0.000
##    .A5                0.405    0.023   17.830    0.000
##    .A6                0.440    0.023   18.753    0.000
##    .A7                0.476    0.025   19.200    0.000
##    .A8                1.057    0.051   20.733    0.000
##    .A9                0.549    0.029   19.162    0.000
##    .A10               0.967    0.047   20.798    0.000
##    .E1                0.649    0.037   17.445    0.000
##    .E2                0.542    0.037   14.569    0.000
##    .E3                0.836    0.042   20.090    0.000
##    .E4                0.686    0.041   16.824    0.000
##    .E5                0.582    0.029   20.411    0.000
##    .E6                1.024    0.052   19.699    0.000
##    .E7                1.139    0.054   20.967    0.000
##    .E8                0.988    0.051   19.214    0.000
##    .E9                0.923    0.044   20.995    0.000
##    .E10               1.162    0.057   20.557    0.000
##    .I1                0.937    0.046   20.304    0.000
##    .I2                0.742    0.038   19.625    0.000
##    .I3                0.784    0.039   20.100    0.000
##    .I4                0.473    0.028   16.892    0.000
##    .I5                0.952    0.047   20.475    0.000
##    .I6                0.820    0.041   19.965    0.000
##    .I7                0.510    0.028   18.526    0.000
##    .I8                0.507    0.029   17.761    0.000
##    .I9                0.455    0.025   18.168    0.000
##    .I10               0.701    0.035   19.987    0.000
##    .P1                0.402    0.031   12.801    0.000
##    .P2                0.608    0.037   16.555    0.000
##    .P3                0.994    0.049   20.247    0.000
##    .P4                0.901    0.045   20.043    0.000
##    .P5                0.792    0.039   20.511    0.000
##    .P6                0.911    0.046   19.993    0.000
##    .P7                1.136    0.055   20.688    0.000
##    .P8                0.759    0.041   18.563    0.000
##    .P9                0.946    0.046   20.587    0.000
##     warmth            0.543    0.047   11.473    0.000
##     liveliness        0.733    0.061   11.928    0.000
##     vigilance         0.289    0.040    7.310    0.000
##     tension           0.993    0.068   14.611    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-58" class="section level3" number="4.4.5">
<h3><span class="header-section-number">4.4.5</span> </h3>
<p>Do the number of model parameters and degrees of freedom reported in the lavaan output agree with the values you
calculated in <a href="in-class-exercises-3.html#dfClass">4.4.2</a>?</p>
<details>
<summary>
Click to show answer
</summary>
<p>Yes, the values should agree. This first part of the lavaan model summary reports the number of model parameters and the
degrees of freedom.</p>
<pre><code>## lavaan 0.6-19 ended normally after 43 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##                                                   Used       Total
##   Number of observations                           894        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              3664.769
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000</code></pre>
<p>In this case, we see that we’ve estimated 84 parameters and we have df = 696.</p>
</details>
<hr />
</div>
<div id="section-59" class="section level3" number="4.4.6">
<h3><span class="header-section-number">4.4.6</span> </h3>
<p>Examine the factor loadings from the model you estimated in <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>, and answer the following
questions.</p>
<ul>
<li>Some of the estimated factor loadings are negative. Why are these particular loadings negative?</li>
<li>Do you think the negative factor loadings are a problem? Explain you reasoning.</li>
<li>Do the estimates make sense given the wording of the observed items and the putative meanings of the latent
constructs?</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<ul>
<li>The negative factor loadings are associated with reverse-coded items. Such items get negative factor loadings because
higher scores on those items reflect lower levels of the latent construct. In other words, reverse coded items have
negative item-scale correlations.
<span class="math inline">\(\\[3pt]\)</span></li>
<li>No, the negative factor loadings are not inherently problematic. Negative factor loadings do not have a deleterious
effect on the definition of the latent factor. That being said, negative factor loadings can complicate the analysis.
<ul>
<li>Trying to set the scale by fixing the factor loading for a reverse coded item can cause estimation problems or
flip the meaning of the latent factor.</li>
<li>We need to be extra careful when placing constraints for hypothesis testing.
<span class="math inline">\(\\[3pt]\)</span></li>
</ul></li>
<li>Yes, the estimated factor loadings largely align with theoretical expectations. For example, the observed items that
appear to reflect interpersonal “warmth” are associated with positive factor loadings for the <em>Warmth</em> factor, and the
reverse coded items that seem to indicate “coldness” have negative factor loadings. The same pattern holds for all four
latent factors.</li>
</ul>
</details>
<hr />
</div>
<div id="section-60" class="section level3" number="4.4.7">
<h3><span class="header-section-number">4.4.7</span> </h3>
<p>Interpret the latent covariances from the model you estimated in <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>.</p>
<ul>
<li>Use the parameter estimates and statistical tests from your model to support your interpretations.</li>
<li>Do the estimates make sense given the putative meanings of the latent constructs?</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<p>The estimated latent covariances largely conform to theoretical expectations. The two “pro-social” factors, <em>Warmth</em> and
<em>Liveliness</em>, are positively associated
<span class="math inline">\((\psi_{2,1} = 0.306\)</span>,
<span class="math inline">\(\textit{SE} = 0.03\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>,
as are the two “anti-social” factors, <em>Vigilance</em> and <em>Tension</em>,
<span class="math inline">\((\psi_{4,3} = 0.299\)</span>,
<span class="math inline">\(\textit{SE} = 0.03\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>.
Furthermore, <em>Warmth</em> negatively correlates with both of the “anti-social” factors
(<em>Vigilance</em>: <span class="math inline">\(\psi_{3,1} = -0.205\)</span>,
<span class="math inline">\(\textit{SE} = 0.022\)</span>,
<span class="math inline">\(p &lt; 0.001\)</span>;
<em>Tension</em>: <span class="math inline">\(\psi_{4,1} = -0.277\)</span>,
<span class="math inline">\(\textit{SE} = 0.032\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>,
and <em>Liveliness</em> negatively correlates with <em>Vigilance</em>
<span class="math inline">\((\psi_{2,3} = -0.123\)</span>,
<span class="math inline">\(\textit{SE} = 0.02\)</span>,
<span class="math inline">\(p &lt; 0.001)\)</span>.
Only <em>Liveliness</em> and <em>Tension</em> are not significantly associated
<span class="math inline">\((\psi_{2,4} = -0.052\)</span>,
<span class="math inline">\(\textit{SE} = 0.033\)</span>,
<span class="math inline">\(p = 0.12)\)</span>.</p>
</details>
<hr />
<p>We can request more information when we summarize a fitted lavaan model by adding additional arguments to the
<code>summary()</code> call. For the purposes of this course, the following options are most useful.</p>
<ul>
<li><code>ci = TRUE</code>: Include confidence intervals for the estimated parameters</li>
<li><code>stadardized = TRUE</code>: Include the standardized parameter estimates</li>
<li><code>rsquare = TRUE</code>: Include the <span class="math inline">\(R^2\)</span> estimates for all endogenous variables in the model</li>
<li><code>fit.measures = TRUE</code>: Include the model fit statistics</li>
<li><code>modindices = TRUE</code>: Include the modification indices</li>
</ul>
<p>For example, the following code prints the summary including 95% confidence intervals for the parameter estimates.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="in-class-exercises-3.html#cb143-1" tabindex="-1"></a><span class="fu">summary</span>(out1<span class="fl">.1</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 43 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##                                                   Used       Total
##   Number of observations                           894        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              3664.769
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   warmth =~                                                             
##     A1                1.000                               1.000    1.000
##     A2                0.907    0.047   19.346    0.000    0.815    0.999
##     A3                0.749    0.049   15.187    0.000    0.653    0.846
##     A4                0.820    0.047   17.303    0.000    0.727    0.913
##     A5                0.914    0.046   19.781    0.000    0.824    1.005
##     A6                0.811    0.044   18.305    0.000    0.724    0.897
##     A7                0.760    0.044   17.301    0.000    0.674    0.846
##     A8               -0.521    0.053   -9.745    0.000   -0.626   -0.416
##     A9               -0.824    0.047  -17.396    0.000   -0.917   -0.731
##     A10              -0.458    0.051   -9.042    0.000   -0.557   -0.358
##   liveliness =~                                                         
##     E1                1.000                               1.000    1.000
##     E2                1.218    0.054   22.461    0.000    1.112    1.324
##     E3                0.611    0.044   13.847    0.000    0.524    0.697
##     E4                1.109    0.053   20.920    0.000    1.005    1.213
##     E5                0.425    0.035   12.009    0.000    0.356    0.495
##     E6                0.791    0.051   15.508    0.000    0.691    0.890
##     E7               -0.292    0.046   -6.351    0.000   -0.382   -0.202
##     E8               -0.896    0.053  -17.039    0.000   -0.999   -0.793
##     E9               -0.241    0.041   -5.856    0.000   -0.322   -0.161
##     E10              -0.538    0.049  -10.950    0.000   -0.634   -0.441
##   vigilance =~                                                          
##     I1                1.000                               1.000    1.000
##     I2                1.196    0.096   12.467    0.000    1.008    1.384
##     I3                1.019    0.088   11.579    0.000    0.847    1.192
##     I4                1.592    0.113   14.142    0.000    1.371    1.812
##     I5                0.900    0.087   10.370    0.000    0.730    1.070
##     I6                1.108    0.093   11.882    0.000    0.925    1.290
##     I7               -1.299    0.096  -13.491    0.000   -1.488   -1.110
##     I8               -1.471    0.106  -13.864    0.000   -1.680   -1.263
##     I9               -1.307    0.096  -13.686    0.000   -1.494   -1.120
##     I10              -1.015    0.086  -11.836    0.000   -1.183   -0.847
##   tension =~                                                            
##     P1                1.000                               1.000    1.000
##     P2                0.902    0.038   23.796    0.000    0.828    0.976
##     P3                0.520    0.039   13.470    0.000    0.444    0.596
##     P4                0.548    0.037   14.689    0.000    0.475    0.622
##     P5                0.390    0.034   11.554    0.000    0.324    0.457
##     P6                0.564    0.038   14.958    0.000    0.490    0.637
##     P7                0.397    0.040    9.949    0.000    0.319    0.475
##     P8               -0.764    0.038  -20.222    0.000   -0.839   -0.690
##     P9               -0.400    0.037  -10.907    0.000   -0.472   -0.328
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   warmth ~~                                                             
##     liveliness        0.306    0.030   10.185    0.000    0.247    0.364
##     vigilance        -0.205    0.022   -9.239    0.000   -0.248   -0.162
##     tension          -0.277    0.032   -8.696    0.000   -0.339   -0.214
##   liveliness ~~                                                         
##     vigilance        -0.123    0.020   -6.114    0.000   -0.162   -0.084
##     tension          -0.052    0.033   -1.555    0.120   -0.117    0.013
##   vigilance ~~                                                          
##     tension           0.299    0.030    9.887    0.000    0.240    0.358
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .A1                0.554    0.030   18.246    0.000    0.494    0.613
##    .A2                0.441    0.024   18.145    0.000    0.393    0.488
##    .A3                0.702    0.035   19.865    0.000    0.632    0.771
##    .A4                0.554    0.029   19.199    0.000    0.497    0.610
##    .A5                0.405    0.023   17.830    0.000    0.361    0.450
##    .A6                0.440    0.023   18.753    0.000    0.394    0.487
##    .A7                0.476    0.025   19.200    0.000    0.427    0.524
##    .A8                1.057    0.051   20.733    0.000    0.957    1.157
##    .A9                0.549    0.029   19.162    0.000    0.493    0.605
##    .A10               0.967    0.047   20.798    0.000    0.876    1.059
##    .E1                0.649    0.037   17.445    0.000    0.576    0.722
##    .E2                0.542    0.037   14.569    0.000    0.469    0.615
##    .E3                0.836    0.042   20.090    0.000    0.754    0.917
##    .E4                0.686    0.041   16.824    0.000    0.606    0.766
##    .E5                0.582    0.029   20.411    0.000    0.526    0.638
##    .E6                1.024    0.052   19.699    0.000    0.922    1.126
##    .E7                1.139    0.054   20.967    0.000    1.032    1.245
##    .E8                0.988    0.051   19.214    0.000    0.887    1.089
##    .E9                0.923    0.044   20.995    0.000    0.837    1.010
##    .E10               1.162    0.057   20.557    0.000    1.051    1.273
##    .I1                0.937    0.046   20.304    0.000    0.847    1.028
##    .I2                0.742    0.038   19.625    0.000    0.668    0.816
##    .I3                0.784    0.039   20.100    0.000    0.708    0.860
##    .I4                0.473    0.028   16.892    0.000    0.418    0.527
##    .I5                0.952    0.047   20.475    0.000    0.861    1.043
##    .I6                0.820    0.041   19.965    0.000    0.739    0.900
##    .I7                0.510    0.028   18.526    0.000    0.456    0.564
##    .I8                0.507    0.029   17.761    0.000    0.451    0.563
##    .I9                0.455    0.025   18.168    0.000    0.406    0.504
##    .I10               0.701    0.035   19.987    0.000    0.632    0.770
##    .P1                0.402    0.031   12.801    0.000    0.341    0.464
##    .P2                0.608    0.037   16.555    0.000    0.536    0.680
##    .P3                0.994    0.049   20.247    0.000    0.898    1.090
##    .P4                0.901    0.045   20.043    0.000    0.813    0.990
##    .P5                0.792    0.039   20.511    0.000    0.717    0.868
##    .P6                0.911    0.046   19.993    0.000    0.822    1.001
##    .P7                1.136    0.055   20.688    0.000    1.028    1.244
##    .P8                0.759    0.041   18.563    0.000    0.679    0.839
##    .P9                0.946    0.046   20.587    0.000    0.856    1.036
##     warmth            0.543    0.047   11.473    0.000    0.450    0.636
##     liveliness        0.733    0.061   11.928    0.000    0.612    0.853
##     vigilance         0.289    0.040    7.310    0.000    0.212    0.367
##     tension           0.993    0.068   14.611    0.000    0.860    1.127</code></pre>
<hr />
</div>
<div id="section-61" class="section level3" number="4.4.8">
<h3><span class="header-section-number">4.4.8</span> </h3>
<p>Summarize the model you estimated in <a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>, and include the standardized parameter estimates and
the <span class="math inline">\(R^2\)</span> values in the summary.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="in-class-exercises-3.html#cb145-1" tabindex="-1"></a><span class="fu">summary</span>(out1<span class="fl">.1</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 43 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        84
## 
##                                                   Used       Total
##   Number of observations                           894        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                              3664.769
##   Degrees of freedom                               696
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   warmth =~                                                             
##     A1                1.000                               0.737    0.704
##     A2                0.907    0.047   19.346    0.000    0.669    0.710
##     A3                0.749    0.049   15.187    0.000    0.552    0.550
##     A4                0.820    0.047   17.303    0.000    0.604    0.630
##     A5                0.914    0.046   19.781    0.000    0.674    0.727
##     A6                0.811    0.044   18.305    0.000    0.597    0.669
##     A7                0.760    0.044   17.301    0.000    0.560    0.630
##     A8               -0.521    0.053   -9.745    0.000   -0.384   -0.350
##     A9               -0.824    0.047  -17.396    0.000   -0.607   -0.634
##     A10              -0.458    0.051   -9.042    0.000   -0.337   -0.324
##   liveliness =~                                                         
##     E1                1.000                               0.856    0.728
##     E2                1.218    0.054   22.461    0.000    1.042    0.817
##     E3                0.611    0.044   13.847    0.000    0.523    0.496
##     E4                1.109    0.053   20.920    0.000    0.949    0.753
##     E5                0.425    0.035   12.009    0.000    0.364    0.430
##     E6                0.791    0.051   15.508    0.000    0.677    0.556
##     E7               -0.292    0.046   -6.351    0.000   -0.250   -0.228
##     E8               -0.896    0.053  -17.039    0.000   -0.767   -0.611
##     E9               -0.241    0.041   -5.856    0.000   -0.206   -0.210
##     E10              -0.538    0.049  -10.950    0.000   -0.460   -0.393
##   vigilance =~                                                          
##     I1                1.000                               0.538    0.486
##     I2                1.196    0.096   12.467    0.000    0.643    0.598
##     I3                1.019    0.088   11.579    0.000    0.548    0.527
##     I4                1.592    0.113   14.142    0.000    0.856    0.780
##     I5                0.900    0.087   10.370    0.000    0.484    0.444
##     I6                1.108    0.093   11.882    0.000    0.596    0.550
##     I7               -1.299    0.096  -13.491    0.000   -0.699   -0.699
##     I8               -1.471    0.106  -13.864    0.000   -0.791   -0.743
##     I9               -1.307    0.096  -13.686    0.000   -0.703   -0.722
##     I10              -1.015    0.086  -11.836    0.000   -0.546   -0.546
##   tension =~                                                            
##     P1                1.000                               0.997    0.844
##     P2                0.902    0.038   23.796    0.000    0.899    0.755
##     P3                0.520    0.039   13.470    0.000    0.518    0.461
##     P4                0.548    0.037   14.689    0.000    0.547    0.499
##     P5                0.390    0.034   11.554    0.000    0.389    0.401
##     P6                0.564    0.038   14.958    0.000    0.562    0.507
##     P7                0.397    0.040    9.949    0.000    0.396    0.348
##     P8               -0.764    0.038  -20.222    0.000   -0.762   -0.658
##     P9               -0.400    0.037  -10.907    0.000   -0.399   -0.380
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   warmth ~~                                                             
##     liveliness        0.306    0.030   10.185    0.000    0.484    0.484
##     vigilance        -0.205    0.022   -9.239    0.000   -0.517   -0.517
##     tension          -0.277    0.032   -8.696    0.000   -0.377   -0.377
##   liveliness ~~                                                         
##     vigilance        -0.123    0.020   -6.114    0.000   -0.267   -0.267
##     tension          -0.052    0.033   -1.555    0.120   -0.061   -0.061
##   vigilance ~~                                                          
##     tension           0.299    0.030    9.887    0.000    0.557    0.557
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .A1                0.554    0.030   18.246    0.000    0.554    0.505
##    .A2                0.441    0.024   18.145    0.000    0.441    0.496
##    .A3                0.702    0.035   19.865    0.000    0.702    0.697
##    .A4                0.554    0.029   19.199    0.000    0.554    0.603
##    .A5                0.405    0.023   17.830    0.000    0.405    0.471
##    .A6                0.440    0.023   18.753    0.000    0.440    0.552
##    .A7                0.476    0.025   19.200    0.000    0.476    0.603
##    .A8                1.057    0.051   20.733    0.000    1.057    0.878
##    .A9                0.549    0.029   19.162    0.000    0.549    0.598
##    .A10               0.967    0.047   20.798    0.000    0.967    0.895
##    .E1                0.649    0.037   17.445    0.000    0.649    0.470
##    .E2                0.542    0.037   14.569    0.000    0.542    0.333
##    .E3                0.836    0.042   20.090    0.000    0.836    0.754
##    .E4                0.686    0.041   16.824    0.000    0.686    0.432
##    .E5                0.582    0.029   20.411    0.000    0.582    0.815
##    .E6                1.024    0.052   19.699    0.000    1.024    0.691
##    .E7                1.139    0.054   20.967    0.000    1.139    0.948
##    .E8                0.988    0.051   19.214    0.000    0.988    0.627
##    .E9                0.923    0.044   20.995    0.000    0.923    0.956
##    .E10               1.162    0.057   20.557    0.000    1.162    0.846
##    .I1                0.937    0.046   20.304    0.000    0.937    0.764
##    .I2                0.742    0.038   19.625    0.000    0.742    0.642
##    .I3                0.784    0.039   20.100    0.000    0.784    0.723
##    .I4                0.473    0.028   16.892    0.000    0.473    0.392
##    .I5                0.952    0.047   20.475    0.000    0.952    0.803
##    .I6                0.820    0.041   19.965    0.000    0.820    0.698
##    .I7                0.510    0.028   18.526    0.000    0.510    0.511
##    .I8                0.507    0.029   17.761    0.000    0.507    0.447
##    .I9                0.455    0.025   18.168    0.000    0.455    0.479
##    .I10               0.701    0.035   19.987    0.000    0.701    0.702
##    .P1                0.402    0.031   12.801    0.000    0.402    0.288
##    .P2                0.608    0.037   16.555    0.000    0.608    0.429
##    .P3                0.994    0.049   20.247    0.000    0.994    0.787
##    .P4                0.901    0.045   20.043    0.000    0.901    0.751
##    .P5                0.792    0.039   20.511    0.000    0.792    0.840
##    .P6                0.911    0.046   19.993    0.000    0.911    0.743
##    .P7                1.136    0.055   20.688    0.000    1.136    0.879
##    .P8                0.759    0.041   18.563    0.000    0.759    0.567
##    .P9                0.946    0.046   20.587    0.000    0.946    0.856
##     warmth            0.543    0.047   11.473    0.000    1.000    1.000
##     liveliness        0.733    0.061   11.928    0.000    1.000    1.000
##     vigilance         0.289    0.040    7.310    0.000    1.000    1.000
##     tension           0.993    0.068   14.611    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     A1                0.495
##     A2                0.504
##     A3                0.303
##     A4                0.397
##     A5                0.529
##     A6                0.448
##     A7                0.397
##     A8                0.122
##     A9                0.402
##     A10               0.105
##     E1                0.530
##     E2                0.667
##     E3                0.246
##     E4                0.568
##     E5                0.185
##     E6                0.309
##     E7                0.052
##     E8                0.373
##     E9                0.044
##     E10               0.154
##     I1                0.236
##     I2                0.358
##     I3                0.277
##     I4                0.608
##     I5                0.197
##     I6                0.302
##     I7                0.489
##     I8                0.553
##     I9                0.521
##     I10               0.298
##     P1                0.712
##     P2                0.571
##     P3                0.213
##     P4                0.249
##     P5                0.160
##     P6                0.257
##     P7                0.121
##     P8                0.433
##     P9                0.144</code></pre>
</details>
<hr />
<p>We can extract specific elements from the fitted lavaan object with the <code>lavInspect()</code> function. For example, the
following code extracts the number of estimated parameters.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="in-class-exercises-3.html#cb147-1" tabindex="-1"></a><span class="fu">lavInspect</span>(out1<span class="fl">.1</span>, <span class="st">&quot;npar&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 84</code></pre>
<hr />
</div>
<div id="section-62" class="section level3" number="4.4.9">
<h3><span class="header-section-number">4.4.9</span> </h3>
<p>Check the help file for the <code>lavInspect()</code> function to see what you can extract from a fittend lavaan object.</p>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="in-class-exercises-3.html#cb149-1" tabindex="-1"></a>?lavInspect</span></code></pre></div>
</details>
<hr />
</div>
<div id="section-63" class="section level3" number="4.4.10">
<h3><span class="header-section-number">4.4.10</span> </h3>
<p>Use the the <code>lavInspect()</code> function to extract the following data from the lavaan object you created in
<a href="in-class-exercises-3.html#cfaEstimationClass1">4.4.4</a>.</p>
<ul>
<li>The factor loading matrix
<ul>
<li>The latent covariance matrix</li>
<li>The estimated <span class="math inline">\(R^2\)</span> values for the indicator variables.</li>
</ul></li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="in-class-exercises-3.html#cb150-1" tabindex="-1"></a><span class="co"># Extract the estimated parameter matrices</span></span>
<span id="cb150-2"><a href="in-class-exercises-3.html#cb150-2" tabindex="-1"></a>parEst <span class="ot">&lt;-</span> <span class="fu">lavInspect</span>(out1<span class="fl">.1</span>, <span class="st">&quot;est&quot;</span>)</span>
<span id="cb150-3"><a href="in-class-exercises-3.html#cb150-3" tabindex="-1"></a></span>
<span id="cb150-4"><a href="in-class-exercises-3.html#cb150-4" tabindex="-1"></a><span class="co"># Print the estimated factor loading matrix</span></span>
<span id="cb150-5"><a href="in-class-exercises-3.html#cb150-5" tabindex="-1"></a>parEst<span class="sc">$</span>lambda</span>
<span id="cb150-6"><a href="in-class-exercises-3.html#cb150-6" tabindex="-1"></a></span>
<span id="cb150-7"><a href="in-class-exercises-3.html#cb150-7" tabindex="-1"></a><span class="co"># Print the estimated latent covariance matrix</span></span>
<span id="cb150-8"><a href="in-class-exercises-3.html#cb150-8" tabindex="-1"></a>parEst<span class="sc">$</span>psi</span>
<span id="cb150-9"><a href="in-class-exercises-3.html#cb150-9" tabindex="-1"></a></span>
<span id="cb150-10"><a href="in-class-exercises-3.html#cb150-10" tabindex="-1"></a><span class="co"># Alternatively, we can directly extract the latent covariance matrix</span></span>
<span id="cb150-11"><a href="in-class-exercises-3.html#cb150-11" tabindex="-1"></a><span class="fu">lavInspect</span>(out1<span class="fl">.1</span>, <span class="st">&quot;cov.lv&quot;</span>)</span>
<span id="cb150-12"><a href="in-class-exercises-3.html#cb150-12" tabindex="-1"></a></span>
<span id="cb150-13"><a href="in-class-exercises-3.html#cb150-13" tabindex="-1"></a><span class="co"># Extract the estimated R^2 values</span></span>
<span id="cb150-14"><a href="in-class-exercises-3.html#cb150-14" tabindex="-1"></a><span class="fu">lavInspect</span>(out1<span class="fl">.1</span>, <span class="st">&quot;r2&quot;</span>)</span></code></pre></div>
</details>
<hr />
<p>Now, we’re going to complicate matters slightly by adding another dimension to our model. We’ll now estimate a
two-dimensional CFA that contains correlated <em>Warmth</em> and <em>Dominance</em> factors.</p>
<p>Defined this new model as follows:</p>
<ul>
<li>Two correlated, reflective latent factors: one <em>Warmth</em> factor and one <em>Dominance</em> factor</li>
<li>10 observed indicators of <em>Warmth</em>: {<code>A1</code>, <code>A2</code>, …, <code>A10</code>}</li>
<li>10 observed indicators of <em>Dominance</em>: {<code>D1</code>, <code>D2</code>, …, <code>D10</code>}</li>
<li>No cross-loadings</li>
<li>No residual correlations</li>
</ul>
<p>Again, this CFA should estimate the default measurement model though which two correlated latent factors generate a set
of 20 observed indicators.</p>
<hr />
</div>
<div id="section-64" class="section level3" number="4.4.11">
<h3><span class="header-section-number">4.4.11</span> </h3>
<p>Sketch a path diagram of the CFA model described above.</p>
<ul>
<li>Use pencil and paper (or the equivalent); don’t generate the diagram programmatically.</li>
</ul>
<hr />
</div>
<div id="cfaSyntax2" class="section level3" number="4.4.12">
<h3><span class="header-section-number">4.4.12</span> </h3>
<p>Define the <code>lavaan</code> model syntax for a two-factor model of the <em>Warmth</em> and <em>Dominance</em> items.</p>
<ul>
<li>Save this syntax as an object in your environment.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="in-class-exercises-3.html#cb151-1" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb151-2"><a href="in-class-exercises-3.html#cb151-2" tabindex="-1"></a><span class="st">warmth    =~ A1 + A2 + A3 + A4 + A5 + A6 + A7 + A8 + A9 + A10</span></span>
<span id="cb151-3"><a href="in-class-exercises-3.html#cb151-3" tabindex="-1"></a><span class="st">dominance =~ D1 + D2 + D3 + D4 + D5 + D6 + D7 + D8 + D9 + D10</span></span>
<span id="cb151-4"><a href="in-class-exercises-3.html#cb151-4" tabindex="-1"></a><span class="st">&#39;</span></span></code></pre></div>
</details>
<hr />
</div>
<div id="cfaEstimation2" class="section level3" number="4.4.13">
<h3><span class="header-section-number">4.4.13</span> </h3>
<p>Estimate the two-factor model you specified in <a href="at-home-exercises-3.html#cfaSyntax2">4.3.10</a>, and summarize the results.</p>
<ul>
<li>Identify the model by fixing the first factor loading of each construct to 1.</li>
<li>Do not estimate any mean structure.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="in-class-exercises-3.html#cb152-1" tabindex="-1"></a><span class="do">## Estimate the one factor model:</span></span>
<span id="cb152-2"><a href="in-class-exercises-3.html#cb152-2" tabindex="-1"></a>out2<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod2, <span class="at">data =</span> cattell)</span>
<span id="cb152-3"><a href="in-class-exercises-3.html#cb152-3" tabindex="-1"></a></span>
<span id="cb152-4"><a href="in-class-exercises-3.html#cb152-4" tabindex="-1"></a><span class="do">## Summarize the results:</span></span>
<span id="cb152-5"><a href="in-class-exercises-3.html#cb152-5" tabindex="-1"></a><span class="fu">summary</span>(out2<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 25 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        41
## 
##                                                   Used       Total
##   Number of observations                           932        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                               823.377
##   Degrees of freedom                               169
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                1.000                           
##     A2                0.867    0.046   18.784    0.000
##     A3                0.772    0.049   15.651    0.000
##     A4                0.813    0.047   17.324    0.000
##     A5                0.905    0.046   19.694    0.000
##     A6                0.794    0.044   18.127    0.000
##     A7                0.768    0.044   17.396    0.000
##     A8               -0.531    0.053  -10.033    0.000
##     A9               -0.822    0.047  -17.566    0.000
##     A10              -0.476    0.050   -9.458    0.000
##   dominance =~                                        
##     D1                1.000                           
##     D2                0.844    0.042   20.132    0.000
##     D3                0.506    0.041   12.294    0.000
##     D4                0.526    0.041   12.783    0.000
##     D5                0.771    0.033   23.080    0.000
##     D6                0.467    0.035   13.265    0.000
##     D7               -0.901    0.040  -22.500    0.000
##     D8               -0.409    0.038  -10.843    0.000
##     D9               -0.655    0.040  -16.557    0.000
##     D10              -0.657    0.046  -14.336    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     dominance         0.135    0.024    5.551    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.550    0.030   18.231    0.000
##    .A2                0.470    0.025   18.639    0.000
##    .A3                0.701    0.035   20.026    0.000
##    .A4                0.559    0.029   19.413    0.000
##    .A5                0.418    0.023   17.972    0.000
##    .A6                0.453    0.024   19.023    0.000
##    .A7                0.492    0.025   19.381    0.000
##    .A8                1.053    0.050   21.098    0.000
##    .A9                0.544    0.028   19.303    0.000
##    .A10               0.969    0.046   21.160    0.000
##    .D1                0.327    0.023   14.501    0.000
##    .D2                0.684    0.036   19.186    0.000
##    .D3                0.846    0.040   20.898    0.000
##    .D4                0.838    0.040   20.834    0.000
##    .D5                0.368    0.021   17.825    0.000
##    .D6                0.605    0.029   20.767    0.000
##    .D7                0.549    0.030   18.154    0.000
##    .D8                0.730    0.035   21.066    0.000
##    .D9                0.699    0.035   20.183    0.000
##    .D10               1.002    0.049   20.602    0.000
##     warmth            0.543    0.047   11.638    0.000
##     dominance         0.695    0.048   14.518    0.000</code></pre>
</details>
<hr />
</div>
<div id="section-65" class="section level3" number="4.4.14">
<h3><span class="header-section-number">4.4.14</span> </h3>
<p>Report the following parameter estimates from the model you estimated in <a href="at-home-exercises-3.html#cfaEstimation2">4.3.11</a>.</p>
<ol style="list-style-type: decimal">
<li>The <code>warmth</code> <span class="math inline">\(\rightarrow\)</span> <code>A3</code> factor loading</li>
<li>The <code>dominance</code> <span class="math inline">\(\rightarrow\)</span> <code>D2</code> factor loading</li>
<li>The latent covariance between <em>warmth</em> and <em>dominance</em></li>
</ol>
<details>
<summary>
Click to show answer
</summary>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\lambda_{3,1} = 0.772\)</span></li>
<li><span class="math inline">\(\lambda_{12,2} = 0.844\)</span></li>
<li><span class="math inline">\(\psi_{2,1} = 0.135\)</span></li>
</ol>
</details>
<hr />
</div>
<div id="section-66" class="section level3" number="4.4.15">
<h3><span class="header-section-number">4.4.15</span> </h3>
<p>Based on the CFA you estimated in <a href="at-home-exercises-3.html#cfaEstimation2">4.3.11</a>, can we infer a significant linear association between <em>Warmth</em>
and <em>Dominance</em>?</p>
<ul>
<li>Use the statistics from your estimated model to justify your conclusion.</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<p>Yes, warmth and dominance are significantly correlated
(<span class="math inline">\(\psi_{2,1} = 0.135\)</span>, <span class="math inline">\(SE = 0.02\)</span>, <span class="math inline">\(z = 5.55\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</p>
</details>
<hr />
</div>
<div id="section-67" class="section level3" number="4.4.16">
<h3><span class="header-section-number">4.4.16</span> </h3>
<p>Use the <code>semPaths()</code> function to draw a path diagram of your estimated CFA.</p>
<ul>
<li>Include the parameter estimates in the diagram.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="in-class-exercises-3.html#cb154-1" tabindex="-1"></a><span class="fu">semPaths</span>(out2<span class="fl">.1</span>, <span class="at">whatLabels =</span> <span class="st">&quot;estimates&quot;</span>)</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-312-1.png" width="672" /></p>
</details>
<hr />
</div>
<div id="cfaEstimation3" class="section level3" number="4.4.17">
<h3><span class="header-section-number">4.4.17</span> </h3>
<p>Estimate a modified version of the two-factor CFA from <a href="at-home-exercises-3.html#cfaEstimation2">4.3.11</a>, and summarize the results.</p>
<ul>
<li>Estimate the mean structure.</li>
<li>Identify the model with the fixed factor method (i.e., standardize the latent variables).</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="in-class-exercises-3.html#cb155-1" tabindex="-1"></a>out2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">cfa</span>(mod2, <span class="at">data =</span> cattell, <span class="at">meanstructure =</span> <span class="cn">TRUE</span>, <span class="at">std.lv =</span> <span class="cn">TRUE</span>)</span>
<span id="cb155-2"><a href="in-class-exercises-3.html#cb155-2" tabindex="-1"></a><span class="fu">summary</span>(out2<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-19 ended normally after 17 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        61
## 
##                                                   Used       Total
##   Number of observations                           932        1000
## 
## Model Test User Model:
##                                                       
##   Test statistic                               823.377
##   Degrees of freedom                               169
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth =~                                           
##     A1                0.737    0.032   23.276    0.000
##     A2                0.639    0.029   22.266    0.000
##     A3                0.569    0.033   17.483    0.000
##     A4                0.598    0.030   19.926    0.000
##     A5                0.666    0.028   23.856    0.000
##     A6                0.585    0.028   21.184    0.000
##     A7                0.566    0.028   20.037    0.000
##     A8               -0.391    0.037  -10.467    0.000
##     A9               -0.605    0.030  -20.298    0.000
##     A10              -0.350    0.036   -9.819    0.000
##   dominance =~                                        
##     D1                0.834    0.029   29.036    0.000
##     D2                0.703    0.034   20.891    0.000
##     D3                0.422    0.034   12.451    0.000
##     D4                0.439    0.034   12.960    0.000
##     D5                0.643    0.026   24.327    0.000
##     D6                0.389    0.029   13.463    0.000
##     D7               -0.751    0.032  -23.630    0.000
##     D8               -0.341    0.031  -10.950    0.000
##     D9               -0.546    0.032  -16.956    0.000
##     D10              -0.548    0.038  -14.589    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   warmth ~~                                           
##     dominance         0.219    0.036    6.041    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                3.755    0.034  109.685    0.000
##    .A2                3.871    0.031  126.109    0.000
##    .A3                3.844    0.033  115.977    0.000
##    .A4                3.687    0.031  117.542    0.000
##    .A5                3.893    0.030  128.008    0.000
##    .A6                3.761    0.029  128.704    0.000
##    .A7                3.894    0.030  131.943    0.000
##    .A8                2.931    0.036   81.503    0.000
##    .A9                2.135    0.031   68.298    0.000
##    .A10               2.462    0.034   71.941    0.000
##    .D1                3.515    0.033  106.132    0.000
##    .D2                3.343    0.036   94.031    0.000
##    .D3                3.605    0.033  108.744    0.000
##    .D4                3.587    0.033  107.897    0.000
##    .D5                3.694    0.029  127.619    0.000
##    .D6                3.615    0.028  126.910    0.000
##    .D7                2.622    0.035   75.893    0.000
##    .D8                2.085    0.030   69.203    0.000
##    .D9                2.855    0.033   87.284    0.000
##    .D10               2.381    0.037   63.692    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .A1                0.550    0.030   18.231    0.000
##    .A2                0.470    0.025   18.639    0.000
##    .A3                0.701    0.035   20.026    0.000
##    .A4                0.559    0.029   19.413    0.000
##    .A5                0.418    0.023   17.972    0.000
##    .A6                0.453    0.024   19.023    0.000
##    .A7                0.492    0.025   19.381    0.000
##    .A8                1.053    0.050   21.098    0.000
##    .A9                0.544    0.028   19.303    0.000
##    .A10               0.969    0.046   21.160    0.000
##    .D1                0.327    0.023   14.501    0.000
##    .D2                0.684    0.036   19.186    0.000
##    .D3                0.846    0.040   20.898    0.000
##    .D4                0.838    0.040   20.834    0.000
##    .D5                0.368    0.021   17.825    0.000
##    .D6                0.605    0.029   20.767    0.000
##    .D7                0.549    0.030   18.154    0.000
##    .D8                0.730    0.035   21.066    0.000
##    .D9                0.699    0.035   20.183    0.000
##    .D10               1.002    0.049   20.602    0.000
##     warmth            1.000                           
##     dominance         1.000</code></pre>
</details>
<hr />
</div>
<div id="section-68" class="section level3" number="4.4.18">
<h3><span class="header-section-number">4.4.18</span> </h3>
<p>Report the following parameter estimates from the model you estimated in <a href="at-home-exercises-3.html#cfaEstimation3">4.3.15</a>.</p>
<ol style="list-style-type: decimal">
<li>The item intercept for <code>A1</code></li>
<li>The item intercept for <code>D5</code></li>
<li>The mean of the <em>Warmth</em> factor</li>
</ol>
<details>
<summary>
Click to show answer
</summary>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\tau_1 = 3.76\)</span></li>
<li><span class="math inline">\(\tau_{15} = 3.69\)</span></li>
<li>This is a bit of a trick question. We fixed the latent means to zero for model identification, so we don’t have an
estimated latent mean for the warmth factor.</li>
</ol>
</details>
<hr />
</div>
<div id="section-69" class="section level3" number="4.4.19">
<h3><span class="header-section-number">4.4.19</span> </h3>
<p>Based on the CFA you estimated in <a href="at-home-exercises-3.html#cfaEstimation3">4.3.15</a>, how strong is the association between <em>Warmth</em> and <em>Dominance</em>?</p>
<ul>
<li>Use the statistics from your estimated model to justify your conclusion.</li>
</ul>
<details>
<summary>
Click to show answer
</summary>
<p>We set the scale by standardizing the latent factors, so we can interpret the latent covariance as a correlation. Hence,
the estimated latent covariance of <span class="math inline">\(\psi_{2,1} = 0.219\)</span> suggests a weak linear association between <em>Warmth</em> and
<em>Dominance</em>.</p>
</details>
<hr />
</div>
<div id="section-70" class="section level3" number="4.4.20">
<h3><span class="header-section-number">4.4.20</span> </h3>
<p>Use the <code>semPaths()</code> function to draw a path diagram of the CFA you estimated in <a href="at-home-exercises-3.html#cfaEstimation3">4.3.15</a>.</p>
<ul>
<li>Include the parameter estimates in the diagram.</li>
</ul>
<details>
<summary>
Click to show code
</summary>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="in-class-exercises-3.html#cb157-1" tabindex="-1"></a><span class="fu">semPaths</span>(out2<span class="fl">.2</span>, <span class="at">whatLabels =</span> <span class="st">&quot;estimates&quot;</span>)</span></code></pre></div>
<p><img src="isem_files/figure-html/unnamed-chunk-316-1.png" width="672" /></p>
</details>
<hr />
<p>End of At-Home Exercises</p>
<hr />

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="at-home-exercises-3.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cfa-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": false,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "search": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
