%%% Title:    ISEM Week 5: CFA II
%%% Author:   Kyle M. Lang (Adapted from Rebecca Kuiper's Summer School Slides)
%%% Created:  2016-XX-XX
%%% Modified: 2025-10-02

\documentclass[10pt]{beamer}
\usetheme{Utrecht}

\usepackage{graphicx}
\usepackage[natbibapa]{apacite}
\usepackage[libertine]{newtxmath}
\usepackage{fancybox}
\usepackage{booktabs}
\usepackage{relsize}
\usepackage{xcolor}
\usepackage{mathtools}
% \usepackage{amsmath}
\usepackage{listings}
\lstnewenvironment{rc}[1][]{\lstset{language=R}}{}

\graphicspath{{images/}}
\usepackage{tikz} 
\usetikzlibrary{arrows,calc,patterns,positioning,shapes,decorations.markings} 
\usetikzlibrary{decorations.pathmorphing} 

\newcommand{\eqit}[1]{\textrm{\textit{#1}}}
\newcommand{\pkg}[1]{\textbf{#1}}
\newcommand{\src}[1]{\texttt{#1}}
\newcommand{\rmsc}[1]{\textrm{\textsc{#1}}}
\newcommand{\mub}[0]{\boldsymbol{\muup}}
\newcommand{\var}[1]{\eqit{var}(#1)}
\newcommand{\cov}[1]{\eqit{cov}(#1)}

\DeclareMathOperator*{\argmin}{\arg\min}

\title{Confirmatory Factor Analysis II}
\subtitle{Introduction to Structural Equation Modeling}
\author{Kyle M. Lang}
\institute{Department of Methodology \& Statistics\\Utrecht University}
\date{}

\begin{document}

<<setup, include = FALSE, cache = FALSE>>=
set.seed(235711)

library(knitr)
library(ggplot2)
library(xtable)
library(dplyr)
library(tidySEM)
library(lavaan)
library(psych)
library(Hmisc)
library(lavaanPlot)
library(semPlot)
library(semptools)

source(here::here("code", "supportFunctions.R"))

options(width = 80)
opts_chunk$set(size = "footnotesize",
               fig.align = "center",
               fig.path = "figure/cfa_estimation-",
               message = FALSE,
               comment = "")
knit_theme$set('edit-kwrite')
@

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[t,plain]
  \titlepage
\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Outline}
  \tableofcontents
\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\sectionslide{Model Estimation}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Model-Implied Statistics}

%----------------------------------------------------------------------------------------------------------------------%
\begin{frame}{Model-Implied Statistics}

  Most statistical estimation algorithms operate by minimizing the difference between two key reference points:

  \vc

  \begin{enumerate}
    \item The \emph{model-implied} statistics/predictions/fitted values
      \begin{itemize}
        \item The sufficient statistics implied by the structure of your model.
        \item Predicted/fitted values produced by your model.
      \end{itemize}

      \vc

    \item The \emph{observed} statistics/values
      \begin{itemize}
        \item The sufficient statistics calculated from the observed data.
        \item The raw outcome values from your dataset.
      \end{itemize}
  \end{enumerate}

  \vb

  The predictions/implied statistics produced by a good model must be simpler than the analogous quantities in the
  observed data.
  \begin{itemize}
    \item A model that exactly replicates the observed data is overfitting.
    \item The inferences from such models won't generalize to the population.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Model-Implied Statistics}

  You should already be familiar with this idea from OLS regression.

  \begin{itemize}
    \item The fitted values are the model implied statistics.
      \begin{align*}
        \hat{Y}_n = \hat{\beta}_0 + \sum_{p = 1}^P \hat{\beta}_p X_{n,p}
      \end{align*}
    \item The raw outcome variable, $Y$, contains the observed values.
    \item Minimize the difference between $\hat{Y}$ and $Y$ to estimate the model.
      \begin{align*}
        \eqit{RSS} = \sum_{n = 1}^N \left( Y_n - \hat{Y}_n \right)^2
      \end{align*}
  \end{itemize}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Hypothesized Model}

  We'll use this toy model to sketch out the intuition for maximum likelihood estimation of CFA models.

  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{align*}
        \alpha &=
        \begin{bmatrix}
          \alpha_1
        \end{bmatrix}
        \quad
        \Psi =
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \\[12pt]
        \tau &=
        \begin{bmatrix}
          \tau_1 \\
          \tau_2 \\
          \tau_3
        \end{bmatrix}
        \quad
        \Lambda =
        \begin{bmatrix}
          \lambda_{11}\\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \\[12pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.7\textwidth]{figures/cfa_three_indicators_means.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{Parameters $\rightarrow$ Implied Statistics}

  The parameter matrices define the model-implied mean vector, $\hat{\mu}$, and covariance matrix, $\hat{\Sigma}$, via
  the following formulas.
  \begin{align*}
    \Sigma &= \Lambda \Psi \Lambda^T + \Theta\\
    \mu &= \tau + \Lambda \alpha
  \end{align*}

  \vb

  By expanding these formulas, we can see how the model reproduces each mean, variance, and covariance.
  \begin{align*}
    \hat{\mu} =
    \begin{bmatrix}
     \tau_1 + \lambda_{11} \alpha_1 \\[3pt]
     \tau_2 + \lambda_{22} \alpha_1 \\[3pt]
     \tau_3 + \lambda_{33} \alpha_1
    \end{bmatrix}
    \quad
    \hat{\Sigma} =
    \begin{bmatrix*}[l]
      \lambda_{11} \psi_{11} \lambda_{11} + \theta_{11} &                                                   &                                                   \\[3pt]
      \lambda_{11} \psi_{11} \lambda_{21}               & \lambda_{21} \psi_{11} \lambda_{21} + \theta_{22} &                                                   \\[3pt]
      \lambda_{11} \psi_{11} \lambda_{31}               & \lambda_{21} \psi_{11} \lambda_{31}               & \lambda_{31} \psi_{11} \lambda_{31} + \theta_{33} \\
    \end{bmatrix*}
  \end{align*}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Model-Implied Statistics for Estimation}

  The estimating algorithm chooses values for $\alpha$, $\tau$, $\Psi$, and $\Lambda$ that minimize the differences
  between the model-implied statistics, $\{ \hat{\mu},\ \hat{\Sigma} \}$, and the sufficient statistics calculated from
  the observed data, $\{ \bar{\mathbf{Y}},\ \mathbf{S} \}$.

  \begin{alignat*}{3}
    \hat{\mu} &=
    \begin{bmatrix}
     \tau_1 + \lambda_{11} \alpha_1 \\[3pt]
     \tau_2 + \lambda_{22} \alpha_1 \\[3pt]
     \tau_3 + \lambda_{33} \alpha_1
    \end{bmatrix}
    \quad
    &
    \hat{\Sigma} &=
    \begin{bmatrix*}[l]
      \lambda_{11} \psi_{11} \lambda_{11} + \theta_{11} &                                                   &                                                   \\[3pt]
      \lambda_{11} \psi_{11} \lambda_{21}               & \lambda_{21} \psi_{11} \lambda_{21} + \theta_{22} &                                                   \\[3pt]
      \lambda_{11} \psi_{11} \lambda_{31}               & \lambda_{21} \psi_{11} \lambda_{31}               & \lambda_{31} \psi_{11} \lambda_{31} + \theta_{33} \\
    \end{bmatrix*}
    \\[12pt]
    \bar{\mathbf{Y}} &=
    \begin{bmatrix}
      \bar{y}_1 \\[3pt]
      \bar{y}_2 \\[3pt]
      \bar{y}_3
    \end{bmatrix}
    &
    \mathbf{S} &=
    \begin{bmatrix*}[l]
      \var{y_1}      &                &           \\[3pt]
      \cov{y_2, y_1} & \var{y_2}      &           \\[3pt]
      \cov{y_3, y_1} & \cov{y_3, y_2} & \var{y_3} \\
    \end{bmatrix*}
  \end{alignat*}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\subsection{Optimization}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Optimization: Intuition}

  We can formulate the familiar OLS objective as an abstract optimization problem at follows.
  \begin{align*}
    f(\beta_0, \beta_1, \ldots, \beta_P) = \argmin_{\beta_0, \beta_1, \ldots, \beta_P} \left\| Y - \hat{Y} \right\|
  \end{align*}

  Applying the same idea to our CFA optimization problem, we get the following formulation.
  \begin{align*}
    f(\Lambda, \Psi) &= \argmin_{\Lambda,\Psi} \left\| \mathrm{Cov}(\mathbf{Y}) - \hat{\Sigma} \right\|\\
    f(\tau, \alpha) &= \argmin_{\tau,\alpha} \left\| \bar{\mathbf{Y}} - \hat{\mu} \right\|
  \end{align*}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Optimization: Objective Function}

  In OLS regression, we minimize the residual sum of squares (RSS).
  \begin{align*}
    RSS = \sum_{n = 1}^N \left( Y_n - \hat{Y}_n \right)^2 
  \end{align*}

  In CFA, we can estimate the model by minimizing the \emph{model deviance}.
  \begin{align*}
    D_M &= -2 \left[ \ell \left( \hat{\Sigma}, \hat{\mu} \right) - \ell \left( \mathbf{S}, \bar{\mathbf{Y}} \right) \right]
  \end{align*}

  Where, $\ell ( \cdot )$ denotes the \emph{loglikelihood} function.
  \begin{itemize}
    \item $\ell \left( \hat{\Sigma}, \hat{\mu} \right)$ returns the loglikelihood value for our estimated model.
    \item $\ell \left( \mathbf{S}, \bar{\mathbf{Y}} \right)$ returns the loglikelihood value for the \emph{saturated
      model}.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Optimization: Loglikelihood Functions}

  The loglikelihood function is a model-based distance metric.
  \vc
  \begin{itemize}
    \item Derived from the assumed data distribution (i.e., multivariate normal)
      \vc
    \item Quantifies the "chances" of your estimated model having generated the observed data
  \end{itemize}
  \begin{align*}
    \ell \left( \hat{\Sigma}, \hat{\mu} \right) &= -\frac{K}{2} \ln (2 \pi) - \frac{1}{2} \ln | \hat{\Sigma} | -
    \frac{1}{2} \sum_{n = 1}^N \left( Y_n - \hat{\mu} \right)^T \hat{\Sigma}^{-1} \left( Y_n - \hat{\mu} \right)
  \end{align*}

  Say we fit two models, $M_a$ and $M_b$, to the same dataset. If $\ell \left( M_a \right)$ is closer to zero, we know
  that  $M_a$ represents the data better than $M_b$ does.
  \vc
  \begin{itemize}
    \item $M_a$'s implied statistics are closer to the observed sufficient statistics.
      \vc
    \item $M_a$'s parameters are more plausible, given the data.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\sectionslide{Model Fit}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Underlying Concepts}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Model Fit: Intuition}

  We want a plausible, parsimonious, and useful model.
  \vc
  \begin{enumerate}
    \item Our model should make theoretical sense.
      \vc
    \item Our model's implied statistics should closely align with the observed sufficient statistics.
      \vc
    \item Our model should be no more complex than necessary.
  \end{enumerate}

  \vb

  We can use \emph{model fit statistics} to evaluate the second and third criteria.
  \vc
  \begin{itemize}
    \item Model fit statistics transform $\hat{D}_M$ into interpretable, comparable, scale-free distance measures.
      \vc
    \item These indices give us practical tools for evaluating how well our model represents the data.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Different Ways to Quantify Fit}

  When evaluating model fit, we need to consider four types of model.
  \vc
  \begin{enumerate}
    \item Our estimated model.
      \vc
    \item The \emph{independence model}
      \begin{itemize}
        \item The worst possible model
        \item All item associations fixed to zero
      \end{itemize}
      \vc
    \item The \emph{saturated model}
      \begin{itemize}
        \item The "best" possible model
        \item Estimates all possible associations
        \item Perfectly reproduces the observed sufficient statistics
      \end{itemize}
      \vc
    \item The \emph{true model}
      \begin{itemize}
        \item The unknown population model that generates the data
        \item Typically simpler than the saturated model
      \end{itemize}
  \end{enumerate}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Model Continuum}

  We can use the \emph{model continuum} diagrammed below to organize the four classes of possible model.
  \vc
  \begin{itemize}
    \item The left side of the continuum represents bad model fit.
      \vc
    \item The right side of the continuum represents good model fit.
  \end{itemize}

  \vb

  \begin{figure}
    \includegraphics[width = 0.9\textwidth]{figures/fit_line_bare.png}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Independence Model}

<<>>=
indMod <- '
A1 ~~ A1
A2 ~~ A2
A3 ~~ A3
O1 ~~ O1
O2 ~~ O2
O3 ~~ O3
'

indOut <- cfa(indMod, data = bfi)
@

\framebreak

<<>>=
partSummary(indOut, 1:4)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Independence Model}
  
<<>>=
lavInspect(indOut, "sigma")
@

<<echo = FALSE, out.width = '0.9\\linewidth', fig.height = 2>>=
semPaths(indOut,
         layout = "tree",
         sizeMan = 10,
         sizeMan2 = 8,
         curve = 3,
         esize = 2,
         asize = 4,
         mar = c(0, 2, 0, 2))
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Saturated Model}
  
<<>>=
satMod <- '
A1 ~~ A1
A2 ~~ A1 + A2
A3 ~~ A1 + A2 + A3
O1 ~~ A1 + A2 + A3 + O1
O2 ~~ A1 + A2 + A3 + O1 + O2
O3 ~~ A1 + A2 + A3 + O1 + O2 + O3
'

satOut <- cfa(satMod, data = bfi)
@

\framebreak

<<>>=
partSummary(satOut, 1:4)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Saturated Model}
  
<<>>=
lavInspect(satOut, "sigma")
@

<<echo = FALSE, out.width = '0.9\\linewidth', fig.height = 2.5>>=
tmp        <- rep(0, 6)
names(tmp) <- lavNames(satOut)

semPaths(satOut,
         layout = "tree",
         sizeMan = 10,
         sizeMan2 = 8,
         curve = 3,
         esize = 2,
         asize = 4,
         mar = c(0, 1, -4, 1),
         DoNotPlot = TRUE) |>
  rotate_resid(tmp) |>
  plot()
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Saturated Model}
  
  The saturated model reproduces the observed sufficient statistics.
  \begin{itemize}
    \item $\hat{\Sigma} = \mathbf{S}$
  \end{itemize}
  
<<>>=
lavInspect(satOut, "sigma") - lavInspect(satOut, "sampstat")$cov
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Measurement Structure}

  We don't estimate any measurement structure in the independence model or in the saturated model.

  \begin{columns}
    \begin{column}{0.5\textwidth}

<<>>=
lavInspect(indOut, "est")$lambda
lavInspect(indOut, "est")$psi
@

    \end{column}
    \begin{column}{0.5\textwidth}

<<>>=
lavInspect(satOut, "est")$lambda
lavInspect(satOut, "est")$psi
@

    \end{column}
  \end{columns}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{Different Ways to Quantify Fit}

  For now, we'll conceptualize model fit as comparing different points on the model continuum introduced above.
  \vc
  \begin{enumerate}
    \item \emph{Absolute Fit}
      \begin{itemize}
        \item How well does the model reproduce the observed sufficient statistics?
        \item How close is our model to some ideal model?
        \item Compare our model to the \emph{saturated model}.
      \end{itemize}
      \vc
    \item \emph{Relative/Incremental/Comparative Fit}
      \begin{itemize}
        \item How much does our model outperform some baseline model?
        \item How much improvement do we achieve over some bad model?
        \item Compare our model to the \emph{independence model}.
      \end{itemize}
  \end{enumerate}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Fit Statistics \& Indices}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{$\chi^2$ Statistic}

  The $\chi^2$ statistic is the most fundamental model fit statistic.
  \vc
  \begin{itemize}
    \item Absolute fit statistic
      \vc
    \item Derived directly from the optimized value of the objective function
      \vc
    \item Allows rigorous hypothesis tests
      \vc
    \item Basis for most other fit indices
  \end{itemize}
  \begin{align*}
    \chi^2 &= D_M\\
    \chi^2 &= N \times F_{ML}
  \end{align*}

  This statistic follows a $\chi^2$ distribution with $df = Q - P$ (i.e., the same DF as the estimated model).

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example Model}

<<>>=
library(lavaan)
library(psych)

mod1 <- '
agree =~ A1 + A2 + A3
open  =~ O1 + O2 + O3
'

out1 <- cfa(mod1, data = bfi)
@

\framebreak

<<>>=
partSummary(out1, 1:4)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Problems with $\chi^2$}

  The $\chi^2$ statistic test for \emph{exact fit}:
  \begin{align*}
    H_0: \hat{\Sigma} = \mathbf{S}\\
    H_1: \hat{\Sigma} \neq \mathbf{S}
  \end{align*}
  This hypothesis is perfectly valid, but it isn't a very interesting or useful for real-world data analysis.
  \begin{itemize}
    \item The $\chi^2$ will almost always reject the null hypothesis.
    \item With a large enough sample, the null hypothesis must be rejected for any model simpler than the exact data
      generating model.
  \end{itemize}

  \begin{figure}
    \includegraphics[width = 0.7\textwidth]{figures/fit_line_chisq.png}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

% \begin{frame}{Problems with $\chi^2$}

%   The $\chi^2$ statistic test for \emph{exact fit}:
%   \begin{align*}
%     H_0: \hat{\Sigma} = \mathbf{S}\\
%     H_1: \hat{\Sigma} \neq \mathbf{S}
%   \end{align*}
%   This hypothesis is perfectly valid, but it isn't a very interesting or useful for real-world data analysis.
%   \begin{itemize}
%     \item The $\chi^2$ will almost always reject the null hypothesis.
%     \item With a large enough sample, the null hypothesis must be rejected for any model other than the exact data
%       generating model.
%     \item We'll reject perfectly good models because of substantively trivial deviations from the population model.
%   \end{itemize}

%   \vc

%   We don't want a model that exactly replicates the sufficient statistics.
%   \begin{itemize}
%     \item The true data generating model is almost certainly too complex to have any practical utility.
%   \end{itemize}

% \end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{Approximate Fit Indices}

  In practice, we won't use the $\chi^2$ test to directly evaluate model fit. We'll use \emph{approximate fit indices}
  (mostly) derived from the $\chi^2$.
  \vc
  \begin{itemize}
    \item We have many (maybe too many) options.
      \vc
    \item \textbf{lavaan} 0.6-19 provides 28 approximate fit measures for a basic CFA.
  \end{itemize}

  \vb

  We'll focus on three complementary and well-balanced indices.
  \vc
  \begin{itemize}
    \item Root Mean Squared Error of Approximation (RMSEA)
      \vc
    \item Comparative Fit Index (CFI)
      \vc
    \item Standardized Root Mean Squared Residual (SRMR)
  \end{itemize}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

% \begin{frame}{Approximate Fit Indices}

%   Let's start by adding the implied $\chi^2$ values for some key anchor points to our model continuum figure.

%   \vc

%   \begin{figure}
%     \includegraphics[width = 0.9\textwidth]{figures/fit_line_chisq.png}
%   \end{figure}

% \end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{RMSEA}

  \begin{columns}
    \begin{column}{0.5\textwidth}
      The RMSEA is a non-normed \emph{absolute fit index} that evaluates deviations from \emph{close fit}.
    \end{column}
    \begin{column}{0.4\textwidth}
      \begin{align*}
        \textrm{RMSEA} = \sqrt{ \frac{ \textrm{max} \left( \chi^2 - df, ~ 0 \right) }{ N \times df } }
      \end{align*}
    \end{column}
  \end{columns}

  \va

  \begin{figure}
    \includegraphics[width = 0.7\textwidth]{figures/fit_line_rmsea2.png}
  \end{figure}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{RMSEA}

  The RMSEA must be non-negative, but has no upper bound.
  \begin{itemize}
    \item $\textrm{RMSEA} \in [0, +\infty)$
  \end{itemize}

  \vb

  The RMSEA will be positive whenever $\chi^2 > df$.
  \begin{itemize}
    \item $\textrm{RMSEA} = 0 ~ \textit{iif} ~ \chi^2 \leq df$
  \end{itemize}

  \vb

  The RMSEA measures deviations from an ideal model, so smaller values represent better fit.
  \begin{align*}
    \textrm{RMSEA} \in
    \begin{cases}
      [0, ~ 0.06] & \Rightarrow ~ \textrm{Good Fit}\\
      (0.06, ~ 0.08] & \Rightarrow ~ \textrm{Acceptable Fit}\\
      (0.08, ~ 0.1] & \Rightarrow ~ \textrm{Marginal Fit}\\
      (0.1, ~ +\infty) & \Rightarrow ~ \textrm{Bad Fit}
    \end{cases}
  \end{align*}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{CFI}

  The CFI is a normed \emph{incremental fit index}.
  \begin{align*}
    \textrm{CFI} = 1 - \frac{
      \textrm{max} \left( \chi^2 - df, ~ 0 \right)
    }{ 
    \textrm{max} \left( \chi_0^2 - df_0, ~ \chi^2 - df, ~ 0 \right)
    }
    \overset{ \stackrel{typical}{cases} }{\rightarrow}
    1 - \frac{\chi^2 - df}{\chi_0^2 - df_0}
  \end{align*}
  We can use the simplified formula on the right in the ordinary situations where $\chi^2 \geq df$, and the baseline
  model fits worse than our target model.
  \vc
  \begin{figure}
    \includegraphics[width = 0.7\textwidth]{figures/fit_line_cfi2.png}
  \end{figure}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{CFI}

  The CFI is a normed index, so it is bounded by 0 and 1.
  \begin{itemize}
    \item $\textrm{CFI} \in [0, 1]$
  \end{itemize}

  \vb

  The CFI = 0 when the estimated and baseline models are equivalent.
  \begin{itemize}
    \item $\textrm{CFI} = 0 ~ \textit{iif} ~ \left[ (\chi^2 - df) - (\chi_0^2 - df_0) \right] = 0$
  \end{itemize}

  \vb

  The CFI = 1 for estimated models that are equivalent to the true model or more complex than the true model.
  \begin{itemize}
    \item $\textrm{CFI} = 1 ~ \textit{iif} ~ \chi^2 \leq df$
  \end{itemize}

  \vb

  The CFI measures improvement over a poor model, so larger values represent better fit.
  \begin{align*}
    \textrm{CFI} \in
    \begin{cases}
      [0.95, ~ 1] & \Rightarrow ~ \textrm{Good Fit}\\
      [0.90, ~ 0.95) & \Rightarrow ~ \textrm{Acceptable Fit}\\
      [0, ~ 0.90) & \Rightarrow ~ \textrm{Bad Fit}
    \end{cases}
  \end{align*}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{SRMR}

  \begin{columns}
    \begin{column}{0.5\textwidth}
      The SRMR is an \emph{absolute fit index} derived from the standardized model residuals.
    \end{column}
    \begin{column}{0.3\textwidth}
      \begin{align*}
        \textrm{SRMR} = \sqrt{
          \frac{
            \sum_{i = 1}^M \sum_{j = 1}^i \left( \frac{s_{ij} - \hat{\sigma}_{ij}}{s_i s_j} \right)^2 
          }{ 
          Q
          } 
        }
      \end{align*}
    \end{column}
  \end{columns}

  \va

  \begin{figure}
    \includegraphics[width = 0.7\textwidth]{figures/fit_line_full2.png}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{SRMR}

  \begin{columns}
    \begin{column}{0.5\textwidth}
      Basically, the SRMR represents the average magnitude of the standardized model residuals.
    \end{column}
    \begin{column}{0.3\textwidth}
      \begin{align*}
        \textrm{SRMR} \approx \textrm{mean} \left[ \textrm{std} \left( \mathbf{S} - \hat{\Sigma} \right) \right]
      \end{align*}
    \end{column}
  \end{columns}

  \va

  \begin{figure}
    \includegraphics[width = 0.7\textwidth]{figures/fit_line_full2.png}
  \end{figure}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{SRMR}

  Technically, the SRMR is a normed index that is bounded by 0 and 1.
  \begin{itemize}
    \item $\textrm{SRMR} \in [0, 1]$
    \item For all real data, $SRMR \ll 1$
  \end{itemize}

  \vb

  The SRMR = 0 when the estimated and saturated models are equivalent.
  \begin{itemize}
    \item $\textrm{SRMR} = 0 ~ \textit{iif} ~ \hat{\Sigma} = \mathbf{S}$
  \end{itemize}

  \vb

  The SRMR measures deviations from a perfectly fitting model, so smaller values represent better fit.
  \begin{align*}
    \textrm{SRMR} \in
    \begin{cases}
      [0, ~ 0.08] & \Rightarrow ~ \textrm{Good Fit}\\
      (0.08, ~ 0.1] & \Rightarrow ~ \textrm{Acceptable Fit}\\
      (0.1, ~ 1] & \Rightarrow ~ \textrm{Bad Fit}
    \end{cases}
  \end{align*}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\subsection{Code Examples}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Target Model}

  We can use the \src{fitMeasures()} function to get model fit statistics.

<<>>=
fit1 <- fitMeasures(out1)

head(fit1, 22) |> round(3)
@

\framebreak

<<>>=
tail(fit1, -22) |> round(3)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Independence Model}

  We can confirm that the baseline stats provided by lavaan match the versions from our explicitly estimated
  independence model.

<<>>=
indFit <- fitMeasures(indOut) |> as.list()
fit1   <- as.list(fit1)

indFit$chisq
fit1$baseline.chisq

indFit$df
fit1$baseline.df
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Example: Edge Cases}

  The saturated model has perfect fit because it perfectly reproduces the observed sufficient statistics.

<<>>=
fitMeasures(satOut, c("chisq", "df", "rmsea", "cfi", "srmr"))
@

\va

Notice how small the independence model's SRMR value is.

<<>>=
indFit$srmr
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Manually Calculating $\chi^2$}

<<>>=
llSat <- logLik(satOut) # saturated model loglikelihood
ll1   <- logLik(out1)   # target model loglikelihood

# Manually calculate the chi-squared stat
-2 * (ll1 - llSat) |> as.numeric()

# Compare to lavaan's version
fit1$chisq
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Manually Calculating CFI}

<<>>=
# Target model stats
chisq1 <- fit1$chisq
df1    <- fit1$df

# Independence model stats
chisq0 <- fit1$baseline.chisq
df0    <- fit1$baseline.df

# Manually calculate the CFI
1 - ((chisq1 - df1) / (chisq0 - df0))

# Compare to lavaan's version
fit1$cfi
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile]{Manually Calculating RMSEA}

<<>>=
# Sample size
n <- fit1$ntotal

# Manually calculate the RMSEA
sqrt((chisq1 - df1) / (n * df1))

# Compare to lavaan's version
fit1$rmsea
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Manually Calculating SRMR}

<<>>=
M <- 6               # No. of observed variables
Q <- M * (M + 1) / 2 # No. of unique elements in S

# Model-implied covariance matrix
sHat <- inspect(out1, "sigma")

# Observed covariance matrix
sObs <- inspect(out1, "sampstat")$cov

# Observed standard deviations
se <- sqrt(diag(sObs))
@

\framebreak

<<>>=
# Sum of squared standardized residuals
x <- 0
for(i in 1:M) {
  for(j in 1:i) {
    x <- x + ( (sObs[i, j] - sHat[i, j]) / (se[i] * se[j]) )^2
  }
}

# Root mean of the above = SRMR
sqrt(x / Q) |> as.numeric()

# Compare to lavaan's version
fit1$srmr
@

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\sectionslide{Model Identification}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Identifying Constraints}

  We must fix some parameters to identify the model.
  \begin{itemize}
    \item For each construct, we need $df \geq 0$.
      \vc
    \item If the construct has three or more indicators:
      \begin{itemize}
        \item Fix one parameter in the covariance model.
        \item Fix one parameter in the mean model.
      \end{itemize}
      \vc
    \item If the construct has two indicators:
      \begin{itemize}
        \item Fix an additional parameter in the covariance model.
      \end{itemize}
      \vc
    \item If the construct has only one indicator:
      \begin{itemize}
        \item Cannot define a latent factor.
      \end{itemize}
  \end{itemize}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\subsection{Under-Identified Models}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Under-Identified: Unconstrained Model}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          \lambda_{11}\\
          \lambda_{21}
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             \\
          0           & \theta_{22}
        \end{bmatrix}
        \\[8pt]
        Q &= \frac{2 (2 + 1)}{2} = 3\\[8pt]
        df &= Q - P\\
           &= 3 - 5 = -2
      \end{align*}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.45\textwidth]{figures/cfa_two_indicators.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Under-Identified: Marker-Variable}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          1\\
          1
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             \\
          0           & \theta_{22}
        \end{bmatrix}
        \\[8pt]
        df &= Q - P\\
           &= 3 - 3 = 0
      \end{align*}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.45\textwidth]{figures/marker_variable_two_indicators.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Under-Identified: Fixed-Factor}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          1
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          \lambda\\
          \lambda
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             \\
          0           & \theta_{22}
        \end{bmatrix}
        \\[8pt]
        df &= Q - P\\
           &= 3 - 3 = 0
      \end{align*}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.45\textwidth]{figures/fixed_factor_two_indicators.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Over-Identified Models}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Over-Identified Models}

  What happens when we have four (or more) indicators?

  \vb

  \begin{columns}
    \begin{column}{0.5\textwidth}

      With 4 indicators, our model contains 14 parameters:
      \begin{itemize}
        \item Four factor loadings
        \item Four residual variances
        \item Four item intercepts
        \item One latent mean
        \item One latent variance
      \end{itemize}

      \begin{align*}
        Q &= \frac{4 (4 + 1)}{2} + 4 = 14\\
        df &= 14 - 14 = 0
      \end{align*}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.8\textwidth]{figures/cfa_four_indicators_means.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{Over-Identified Models}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      With 5 indicators, we have 17 model parameters:
      \begin{itemize}
        \item Five factor loadings
        \item Five residual variances
        \item Five item intercepts
        \item One latent mean
        \item One latent variance
      \end{itemize}

      \begin{align*}
        Q &= \frac{5 (5 + 1)}{2} + 5 = 20\\
        df &= 20 - 17 = 3
      \end{align*}

    \end{column}
    \begin{column}{0.5\textwidth}

      With 6 indicators, we have 20 model parameters:
      \begin{itemize}
        \item Six factor loadings
        \item Six residual variances
        \item Six item intercepts
        \item One latent mean
        \item One latent variance
      \end{itemize}

      \begin{align*}
        Q &= \frac{6 (6 + 1)}{2} + 6 = 27\\
        df &= 27 - 20 = 7
      \end{align*}

    \end{column}
  \end{columns}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Over-Identified Models}

  With four indicators, we automatically have $df \geq 0$ without imposing any scaling constraints.
  \begin{itemize}
    \item Can we directly estimate the unconstrained model?
  \end{itemize}

<<echo = FALSE, include = FALSE>>=
dataDir <- "data"
sapi <- read.table(here::here(dataDir, "sapi.txt"),
                   header = TRUE,
                   na.strings = "-999")
@

<<warnings = TRUE>>=
mod1 <- '
fun =~ Q77 + Q84 + Q170 + Q196 
'

fit1 <- lavaan(mod1,
               data          = sapi,
               auto.var      = TRUE,
               meanstructure = TRUE,
               int.ov.free   = TRUE, 
               int.lv.free   = TRUE)
@

Hmmm...I guess not.

\framebreak

<<>>=
partSummary(fit1, 1:4)
@

\framebreak

<<>>=
partSummary(fit1, 7:8)
@

\framebreak

<<>>=
partSummary(fit1, 9)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsubsection{Why constrain over-identified models?}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Why $df \geq 0$ is Not Enough}

  In the above example, the data contain enough information to define our model parameters, but that's not enough.
  \vc
  \begin{itemize}
    \item We still need scaling constraints.
      \vc
    \item The estimation algorithm needs an anchor point from which to extrapolate the relative values of the model
      parameters.
      \vc
    \item Without any scaling constraints, an infinite number of parameter matrices will produce the same $\hat{\mu}$
      and $\hat{\Sigma}$.
      \vc
    \item An infinite number of solutions are equally good.
  \end{itemize}

<<>>=
## Fit a model to get some example parameters:
mod1 <- '
fun   =~ Q77 + Q84 + Q170 + Q196 
liked =~ Q44 + Q63 + Q76  + Q98
'
  
fit1 <- cfa(mod1, data = sapi, effect.coding = TRUE)
@

\framebreak

<<>>=
## Extract the estimated factor loadings and latent covariance matrix:
(lambda <- inspect(fit1, "est")$lambda)
(psi <- inspect(fit1, "est")$psi)
@

\framebreak

<<>>=
## Extract the estimated residual variances:
(theta <- inspect(fit1, "est")$theta)
@

\framebreak

<<>>=
## Manually compute the model-implied covariance matrix:
(sigma  <- lambda %*% psi %*% t(lambda) + theta)
@

\framebreak

<<>>=
## Randomly sample an arbitrary scaling factor:
(a <- runif(1, 1, 2))

## Rescale all factor loadings by a factor of a:
(lambda2 <- lambda * a)
@

\framebreak

<<>>=
## Rescale the latent covariance matrix by a factor of (1 / a^2):
(psi2 <- psi / a^2)

## Compute the model-implied covariance matrix using the rescaled parameters:
(sigma2  <- lambda2 %*% psi2 %*% t(lambda2) + theta)
@

\framebreak

<<>>=
## Compare the two model-implied covariance matrices:
all.equal(sigma, sigma2)

## Repeat the experiment 100 times:
out <- rep(NA, 100)
for(i in 1:100) {
  a <- runif(1, 1, 2)

  lambda2 <- lambda * a
  psi2    <- psi / a^2
  sigma2  <- lambda2 %*% psi2 %*% t(lambda2) + theta

  out[i] <- all.equal(sigma, sigma2)
}

## Always the same result?
all(out)
@

\end{frame}


\watermarkon %---------------------------------------------------------------------------------------------------------%

\sectionslide{Example}

%----------------------------------------------------------------------------------------------------------------------%

\def\iw{45mm}\relax     % Indicator node width
\def\fw{20mm}\relax     % Factor node width
\def\gap{0.6}\relax     % Spread between indicator nodes
\def\offset{30mm}\relax % Vertical offset between construct submodels

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Example: Hypothesized Model}

  \begin{columns}
    \begin{column}{0.45\textwidth}

      Let's revisit the example SAPI analysis from last week.
      \vc
      \begin{itemize}
        \item We'll estimate the two-factor CFA shown to the right.
      \end{itemize}

    \end{column}
    \begin{column}{0.55\textwidth}

      \begin{figure}
        \scalebox{0.5}{
          \begin{tikzpicture}[
              indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
              factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
              reg/.style = {->, very thick},
              cov/.style = {<->, very thick}
            ]
            \usetikzlibrary{shapes.geometric}

            %% F1 Nodes
            \node[factor, draw, yshift = \offset] at (0, 0) (f1) {
              \parbox{\fw}{\centering Having\\Fun}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, 3*\gap) (i1) {
              \parbox{\iw}{Item 77:\\I enjoy telling funny stories}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, \gap) (i2) {
              \parbox{\iw}{Item 84:\\I am a good storyteller}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -\gap) (i3) {
              \parbox{\iw}{Item 170:\\I laugh a lot}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -3*\gap) (i4) {
              \parbox{\iw}{Item 196:\\I make others laugh}
            };

            %% F1 Arrows
            \draw[reg] (f1.east) -- (i1.west);
            \draw[reg] (f1.east) -- (i2.west);
            \draw[reg] (f1.east) -- (i3.west);
            \draw[reg] (f1.east) -- (i4.west);

            %% F2 Nodes
            \node[factor, draw, yshift = -\offset] at (0, 0) (f2) {
              \parbox{\fw}{\centering Being\\Liked}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, 3*\gap) (i5) {
              \parbox{\iw}{Item 44:\\I am liked by everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, \gap) (i6) {
              \parbox{\iw}{Item 63:\\I chat to everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -\gap) (i7) {
              \parbox{\iw}{Item 76:\\I have many friends}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -3*\gap) (i8) {
              \parbox{\iw}{Item 98:\\I have good social skills}
            };

            %% F2 Arrows
            \draw[reg] (f2.east) -- (i5.west);
            \draw[reg] (f2.east) -- (i6.west);
            \draw[reg] (f2.east) -- (i7.west);
            \draw[reg] (f2.east) -- (i8.west);

            %% Latent Covariance
            \path[cov] (f1.west) edge [bend right] (f2.west);

          \end{tikzpicture}
        }
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}


%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Model Estimation}

  Load the SAPI data.

<<>>=
dataDir <- "data"
sapi <- read.table(here::here(dataDir, "sapi.txt"),
                   header = TRUE,
                   na.strings = "-999")
@

  Specify the \pkg{lavaan} model syntax for the SAPI extraversion CFA.

<<>>=
mod1 <- '
fun   =~ Q77 + Q84 + Q170 + Q196 
liked =~ Q44 + Q63 + Q76  + Q98
'
@

Use the \src{cfa()} function to estimate the model.

<<>>=
library(lavaan)
out1 <- cfa(mod1, data = sapi, std.lv = TRUE)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Model Evaluation}

<<>>=
partSummary(out1, 1:4)
@

\framebreak

<<>>=
partSummary(out1, 5:7)
@

\framebreak

<<>>=
partSummary(out1, 8:9)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Model Evaluation}

<<>>=
inspect(out1, "r2")
fitMeasures(out1) |> head(22) |> round(3)
@

\framebreak

<<>>=
fitMeasures(out1) |> tail(-22) |> round(3)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

% \begin{frame}[fragile, allowframebreaks]{Example: Compare Scaling Methods}

%   We only need to change one option to implement the fixed-factor method.
%   \begin{itemize}
%     \item The \src{std.lv = TRUE} option (i.e., standardized latent variables)
%       applies the appropriate constraints.
%   \end{itemize}

% <<>>=
% out2 <- cfa(mod1, data = sapi)
% @

% \end{frame}

%----------------------------------------------------------------------------------------------------------------------%

% \begin{frame}[fragile, allowframebreaks]{Example: Fixed Factor}

% <<>>=
% partSummary(out2, 1:4)
% @

% \framebreak

% <<>>=
% partSummary(out2, 5:7)
% @

% \framebreak

% <<>>=
% partSummary(out2, 8:9)
% @

% \end{frame}

% %----------------------------------------------------------------------------------------------------------------------%

% \begin{frame}[fragile, allowframebreaks]{Example: Fixed Factor}

% <<>>=
% inspect(out2, "r2")
% fitMeasures(out2) |> head(22) |> round(3)
% @

% \framebreak

% <<>>=
% fitMeasures(out2) |> tail(-22) |> round(3)
% @

% \end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Compare Scaling Methods}

<<>>=
# Re-estimate the model with marker-variable identification
out2 <- cfa(mod1, data = sapi)

inspect(out1, "est")$lambda - inspect(out2, "est")$lambda
inspect(out1, "est")$psi - inspect(out2, "est")$psi
@

\framebreak

Both models partition the indicators' variance in the same way.

<<>>=
inspect(out1, "r2") - inspect(out2, "r2")
inspect(out1, "est")$theta - inspect(out2, "est")$theta
@

\framebreak

Both models produce equivalent representations of the data.

<<>>=
all.equal(fitMeasures(out1), fitMeasures(out2))
inspect(out1, "sigma") - inspect(out2, "sigma")
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\end{document}
