%%% Title:    ISEM Week 4: CFA Intro
%%% Author:   Kyle M. Lang (Adapted from Caspar's TCSM slides and Rebecca Kuiper's Summer School Slides)
%%% Created:  2016-XX-XX
%%% Modified: 2025-09-24

\documentclass[10pt]{beamer}
\usetheme{Utrecht}

\usepackage{graphicx}
\usepackage[natbibapa]{apacite}
\usepackage[libertine]{newtxmath}
\usepackage{fancybox}
\usepackage{booktabs}
\usepackage{relsize}
\usepackage{xcolor}
\usepackage{mathtools}
% \usepackage{amsmath}
\usepackage{listings}
\lstnewenvironment{rc}[1][]{\lstset{language=R}}{}

\graphicspath{{images/}}
\usepackage{tikz} 
\usetikzlibrary{arrows,calc,patterns,positioning,shapes,decorations.markings} 
\usetikzlibrary{decorations.pathmorphing} 

\newcommand{\eqit}[1]{\textrm{\textit{#1}}}
\newcommand{\pkg}[1]{\textbf{#1}}
\newcommand{\src}[1]{\texttt{#1}}
\newcommand{\rmsc}[1]{\textrm{\textsc{#1}}}
\newcommand{\mub}[0]{\boldsymbol{\muup}}
\newcommand{\var}[1]{\eqit{var}(#1)}
\newcommand{\cov}[1]{\eqit{cov}(#1)}

\DeclareMathOperator*{\argmin}{\arg\min}

\title{Confirmatory Factor Analysis I}
\subtitle{Introduction to Structural Equation Modeling}
\author{Kyle M. Lang}
\institute{Department of Methodology \& Statistics\\Utrecht University}
\date{}

\begin{document}

<<setup, include = FALSE, cache = FALSE>>=
set.seed(235711)

library(knitr)
library(ggplot2)
library(xtable)
library(dplyr)
library(tidySEM)
library(lavaan)
library(psych)
library(Hmisc)
library(lavaanPlot)

source(here::here("code", "supportFunctions.R"))

options(width = 80)
opts_chunk$set(size = "footnotesize",
               fig.align = "center",
               fig.path = "figure/cfa_intro-",
               message = FALSE,
               comment = "")
knit_theme$set('edit-kwrite')
@

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[t,plain]
  \titlepage
\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Outline}
  \tableofcontents
\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\sectionslide{General Ideas}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Working Definitions}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Latent Variables}

  A \emph{latent variable} is simply an unobservable variable
  \begin{itemize}
    \item Usually something we want to analyze
    \item The mathematical formalization of a \emph{Hypothetical Construct}
  \end{itemize}

  \va

  Latent variables are very common.

  \begin{itemize}
    \item A patient's current mood
    \item The approval rate of a political leader
    \item The health of an ecosystem
    \item The number of "calories" burned by an hour of cardio training
    \item The useful lifespan of an industrial machine
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Factor Analysis}

  \emph{Factor analysis} (FA) is a statistical method for estimating latent variables.

  \begin{itemize}
    \item We estimate a set of latent variables that parsimoniously explain the relations among a pool of observed
      variables.
    \item Factor analyses can be exploratory (\emph{Exploratory Factor Analysis}, EFA) or confirmatory
      (\emph{Confirmatory Factor Analysis}, CFA).
  \end{itemize}

  \va

  In FA, we are primarily interested in estimating the underlying \emph{measurement model}.

  \begin{itemize}
    \item The latent structure through which a set of latent variables generate a set of observed items.
    \item Hence, principal components analysis (PCA) is not true FA.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Latent Factors}

  A \emph{latent factor} or \emph{latent construct} is the specific type of latent variable that we're estimating in FA.

  \begin{itemize}
    \item To estimate a latent factor, we need multiple, substantively overlapping \emph{indicator variables}.
    \item All latent factors are latent variables, but not all latent variables are latent factors.
  \end{itemize}
  
  \va

  Latent factors are very common in social and behavior science because we often use multi-item questionnaire to measure
  the various unobservable aspects of society and human experience.

  \begin{itemize}
    \item Mental health screeners (e.g., Beck Depression Inventory, Child Behavior Checklist)
    \item Intelligence tests (e.g., WAIS, WISC)
    \item Customer satisfaction surveys
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Indicator Variables}

  The \emph{indicator variables} are the observed variables that we use to estimate a latent factor.
  
  \begin{itemize}
    \item The latent factor is never observed, so we need to infer its characteristics from the information provided by
      our observed data.
    \item A \emph{measurement model} is a one-to-many mapping of latent factors onto indicator variables.
  \end{itemize}

  \va

  Indicator variables go by many names
  
  \begin{itemize}
    \item Indicators
    \item Observed variables
    \item Observed items
    \item Pretty much any sensible combination of the words: \emph{observed}, \emph{variable}, \emph{item},
      \emph{indicator}
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Intuition}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Example CFA}
  
  \begin{figure}
    \includegraphics[width = 0.9\textwidth]{figures/cfa_two_factors.pdf}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{CFA Intuition}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.9\textwidth]{figures/venn_diagram_blank.png}
      \end{figure}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.9\textwidth]{figures/full_cfa_blank.png}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Partitioning Variance}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.9\textwidth]{figures/venn_diagram_filled2.png}
      \end{figure}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.9\textwidth]{figures/partitioned_covariance_matrix_filled3.png}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{CFA as Partitioned Variance}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.9\textwidth]{figures/venn_diagram_filled3.png}
      \end{figure}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.9\textwidth]{figures/full_cfa_filled.png}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\sectionslide{Different Types of Factor Analysis}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Confirmatory or Exploratory?}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Two Subscales of Extraversion}

  \rmsc{Having Fun}
  \begin{itemize}
    \item Item 77: I enjoy telling funny stories
    \item Item 84: I am a good storyteller
    \item Item 170: I laugh a lot
    \item Item 196: I make others laugh
  \end{itemize}

  \va

  \rmsc{Being Liked}
  \begin{itemize}
    \item Item 44: I am liked by everyone
    \item Item 63: I chat to everyone
    \item Item 76: I have many friends
    \item Item 98: I have good social skills
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\def\iw{45mm}\relax     % Indicator node width
\def\fw{20mm}\relax     % Factor node width
\def\gap{0.6}\relax     % Spread between indicator nodes
\def\offset{30mm}\relax % Vertical offset between construct submodels

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Exploratory Factor Analysis}

  \begin{columns}
    \begin{column}{0.45\textwidth}

      \begin{itemize}
        \item All items load onto all factors
        \item No hypothesized measurement model
        \item Estimating latent covariances is optional
          \begin{itemize}
            \item Oblique factors $\rightarrow$ Estimated
            \item Orthogonal factors $\rightarrow$ Fixed
          \end{itemize}
        \item Solution is not unique
        \item Use rotation to improve interpretability
      \end{itemize}

    \end{column}
    \begin{column}{0.55\textwidth}

      \begin{figure}
        \scalebox{0.5}{
          \begin{tikzpicture}[
              indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
              factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
              reg/.style = {->, very thick},
              cov/.style = {<->, very thick, dashed}
            ]

            \usetikzlibrary{shapes.geometric}

            %% F1 Nodes
            \node[factor, draw, yshift = \offset] at (0, 0) (f1) {
              \parbox{\fw}{\centering Having\\Fun}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, 3*\gap) (i1) {
              \parbox{\iw}{Item 77:\\I enjoy telling funny stories}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, \gap) (i2) {
              \parbox{\iw}{Item 84:\\I am a good storyteller}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -\gap) (i3) {
              \parbox{\iw}{Item 170:\\I laugh a lot}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -3*\gap) (i4) {
              \parbox{\iw}{Item 196:\\I make others laugh}
            };

            %% F1 Arrows
            \draw[reg] (f1.east) -- (i1.west);
            \draw[reg] (f1.east) -- (i2.west);
            \draw[reg] (f1.east) -- (i3.west);
            \draw[reg] (f1.east) -- (i4.west);

            %% F2 Nodes
            \node[factor, draw, yshift = -\offset] at (0, 0) (f2) {
              \parbox{\fw}{\centering Being\\Liked}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, 3*\gap) (i5) {
              \parbox{\iw}{Item 44:\\I am liked by everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, \gap) (i6) {
              \parbox{\iw}{Item 63:\\I chat to everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -\gap) (i7) {
              \parbox{\iw}{Item 76:\\I have many friends}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -3*\gap) (i8) {
              \parbox{\iw}{Item 98:\\I have good social skills}
            };

            %% F2 Arrows
            \draw[reg] (f2.east) -- (i5.west);
            \draw[reg] (f2.east) -- (i6.west);
            \draw[reg] (f2.east) -- (i7.west);
            \draw[reg] (f2.east) -- (i8.west);

            %% F1 Cross-loadings
            \draw[reg, red] (f1.east) -- (i5.west);
            \draw[reg, red] (f1.east) -- (i6.west);
            \draw[reg, red] (f1.east) -- (i7.west);
            \draw[reg, red] (f1.east) -- (i8.west);

            %% F2 Cross-loadings
            \draw[reg, blue] (f2.east) -- (i1.west);
            \draw[reg, blue] (f2.east) -- (i2.west);
            \draw[reg, blue] (f2.east) -- (i3.west);
            \draw[reg, blue] (f2.east) -- (i4.west);

            %% Latent Covariance
            \path[cov] (f1.west) edge [bend right] (f2.west);

          \end{tikzpicture}
        } % end \scalebox{}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Confirmatory Factor Analysis}

  \begin{columns}
    \begin{column}{0.45\textwidth}

      \begin{itemize}
        \item The statistical model represents the hypothesized measurement model
        \item No cross-loadings unless they're predicted by theory
        \item Almost always estimate the latent covariances
        \item A unique solution exists
      \end{itemize}

    \end{column}
    \begin{column}{0.55\textwidth}

      \begin{figure}
        \scalebox{0.5}{
          \begin{tikzpicture}[
              indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
              factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
              reg/.style = {->, very thick},
              cov/.style = {<->, very thick}
            ]
            \usetikzlibrary{shapes.geometric}

            %% F1 Nodes
            \node[factor, draw, yshift = \offset] at (0, 0) (f1) {
              \parbox{\fw}{\centering Having\\Fun}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, 3*\gap) (i1) {
              \parbox{\iw}{Item 77:\\I enjoy telling funny stories}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, \gap) (i2) {
              \parbox{\iw}{Item 84:\\I am a good storyteller}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -\gap) (i3) {
              \parbox{\iw}{Item 170:\\I laugh a lot}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -3*\gap) (i4) {
              \parbox{\iw}{Item 196:\\I make others laugh}
            };

            %% F1 Arrows
            \draw[reg] (f1.east) -- (i1.west);
            \draw[reg] (f1.east) -- (i2.west);
            \draw[reg] (f1.east) -- (i3.west);
            \draw[reg] (f1.east) -- (i4.west);

            %% F2 Nodes
            \node[factor, draw, yshift = -\offset] at (0, 0) (f2) {
              \parbox{\fw}{\centering Being\\Liked}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, 3*\gap) (i5) {
              \parbox{\iw}{Item 44:\\I am liked by everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, \gap) (i6) {
              \parbox{\iw}{Item 63:\\I chat to everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -\gap) (i7) {
              \parbox{\iw}{Item 76:\\I have many friends}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -3*\gap) (i8) {
              \parbox{\iw}{Item 98:\\I have good social skills}
            };

            %% F2 Arrows
            \draw[reg] (f2.east) -- (i5.west);
            \draw[reg] (f2.east) -- (i6.west);
            \draw[reg] (f2.east) -- (i7.west);
            \draw[reg] (f2.east) -- (i8.west);

            %% Latent Covariance
            \path[cov] (f1.west) edge [bend right] (f2.west);

          \end{tikzpicture}
        }
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\subsection{Flavors of Latent Construct}

%----------------------------------------------------------------------------------------------------------------------%

\subsubsection{Reflective Constructs}

%----------------------------------------------------------------------------------------------------------------------%

\def\fw{20mm}\relax  % Factor node width
\def\iw{45mm}\relax  % Indicator node width
\def\rw{7mm}\relax  % Residual node width
\def\gap{0.75}\relax % Spread between indicator nodes

\begin{frame}{Reflective Constructs}

  \begin{figure}
    \scalebox{0.7}{
      \begin{tikzpicture}[
          indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
          factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
          residual/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
          right_arrow/.style = {->, very thick},
          left_arrow/.style = {<-, very thick},
          double_arrow/.style = {<->, very thick},
          resid_arrow/.style = {<->, thick}
        ]
        \usetikzlibrary{shapes.geometric}

        %% Nodes
        \node[factor, draw] at (0, 0) (latent) {
          \parbox{\fw}{\centering Extraversion}
        };

        \node[indicator, right = 2cm of latent] at (2, 3*\gap) (i1) {
          \parbox{\iw}{Item 77:\\I enjoy telling funny stories}
        };
        \node[residual, right = 0.5cm of i1] (u1) {
          \parbox{\rw}{\centering u77}
        };

        \node[indicator, right = 2cm of latent] at (2, \gap) (i2) {
          \parbox{\iw}{Item 84:\\I am a good storyteller}
        };
        \node[residual, right = 0.5cm of i2] (u2) {
          \parbox{\rw}{\centering u84}
        };

        \node[indicator, right = 2cm of latent] at (2, -\gap) (i3) {
          \parbox{\iw}{Item 170:\\I laugh a lot}
        };
        \node[residual, right = 0.5cm of i3] (u3) {
          \parbox{\rw}{\centering u170}
        };

        \node[indicator, right = 2cm of latent] at (2, -3*\gap) (i4) {
          \parbox{\iw}{Item 196:\\I make others laugh}
        };
        \node[residual, right = 0.5cm of i4] (u4) {
          \parbox{\rw}{\centering u196}
        };

        %% Arrows
        \draw[double_arrow] ($(latent.north) + (0.39, 0)$) arc (-40:220:0.5);

        \draw[right_arrow] (latent.east) -- (i1.west);
        \draw[right_arrow] (latent.east) -- (i2.west);
        \draw[right_arrow] (latent.east) -- (i3.west);
        \draw[right_arrow] (latent.east) -- (i4.west);

        \draw[left_arrow] (i1.east) -- (u1.west);
        \draw[left_arrow] (i2.east) -- (u2.west);
        \draw[left_arrow] (i3.east) -- (u3.west);
        \draw[left_arrow] (i4.east) -- (u4.west);

        \draw[resid_arrow] ($(u1.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u2.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u3.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u4.east) + (0, 0.18)$) arc (150:-150:0.35);

      \end{tikzpicture}
    }
  \end{figure}

  In a reflective measurement model, the items are the dependent variables, and
  the latent factor is the independent variable.
  \begin{itemize}
    \item The observed items are dependent variables.
    \item The latent factor is causing the items to take the values we observe.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\def\fw{20mm}\relax % Factor node width
\def\rw{5mm}\relax  % Residual node width
\def\gap{0.5}\relax % Spread between indicator nodes

\begin{frame}{Reflective Constructs}

  \begin{figure}
    \scalebox{0.7}{
      \begin{tikzpicture}[
          indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
          factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
          residual/.style = {ellipse, draw = black, very thick, minimum size = 7mm},
          right_arrow/.style = {->, very thick},
          left_arrow/.style = {<-, very thick},
          double_arrow/.style = {<->, very thick},
          resid_arrow/.style = {<->, thick}
        ]
        \usetikzlibrary{shapes.geometric}

        %% Nodes
        \node[factor, draw] at (0, 0) (latent) {
          \parbox{\fw}{\centering True\\Temperature}
        };

        \node[indicator, right = 2cm of latent] at (2, 3*\gap) (i1) {
          Thermometer Reading 1
        };
        \node[residual, right = 0.5cm of i1] (u1) {
          \parbox{\rw}{\centering u1}
        };

        \node[indicator, right = 2cm of latent] at (2, \gap) (i2) {
          Thermometer Reading 2
        };
        \node[residual, right = 0.5cm of i2] (u2) {
          \parbox{\rw}{\centering u2}
        };

        \node[indicator, right = 2cm of latent] at (2, -\gap) (i3) {
          Thermometer Reading 3
        };
        \node[residual, right = 0.5cm of i3] (u3) {
          \parbox{\rw}{\centering u3}
        };

        \node[indicator, right = 2cm of latent] at (2, -3*\gap) (i4) {
          Thermometer Reading 4
        };
        \node[residual, right = 0.5cm of i4] (u4) {
          \parbox{\rw}{\centering u4}
        };

        %% Arrows
        \draw[double_arrow] ($(latent.north) + (0.39, 0)$) arc (-40:220:0.5);

        \draw[right_arrow] (latent.east) -- (i1.west);
        \draw[right_arrow] (latent.east) -- (i2.west);
        \draw[right_arrow] (latent.east) -- (i3.west);
        \draw[right_arrow] (latent.east) -- (i4.west);

        \draw[left_arrow] (i1.east) -- (u1.west);
        \draw[left_arrow] (i2.east) -- (u2.west);
        \draw[left_arrow] (i3.east) -- (u3.west);
        \draw[left_arrow] (i4.east) -- (u4.west);

        \draw[resid_arrow] ($(u1.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u2.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u3.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u4.east) + (0, 0.18)$) arc (150:-150:0.35);

      \end{tikzpicture}
    }
  \end{figure}

  \vspace{5mm}

  The true temperature is the underlying (unobserved) factor that produces
  thermometer readings.
  \begin{itemize}
    \item Any given thermometer reading is only an imperfect reflection of the
      true temperature.
    \item Multiple readings increase the reliability of our temperature estimate.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\def\fw{15mm}\relax % Factor node width
\def\iw{20mm}\relax % Indicator node width

\begin{frame}{Reflective Constructs}

  \begin{figure}
    \scalebox{0.7}{
      \begin{tikzpicture}[
          indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
          factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
          residual/.style = {ellipse, draw = black, very thick, minimum size = 7mm},
          right_arrow/.style = {->, very thick},
          left_arrow/.style = {<-, very thick},
          double_arrow/.style = {<->, very thick},
          resid_arrow/.style = {<->, thick}
        ]
        \usetikzlibrary{shapes.geometric}

        %% Nodes
        \node[factor, draw] at (0, 0) (latent) {
          \parbox{\fw}{\centering Viral\\Infection}
        };
        \node[indicator, right = 2cm of latent] at (2, 3*\gap) (i1) {
          \parbox{\iw}{Muscle Ache}
        };
        \node[residual, right = 0.5cm of i1] (u1) {
          \parbox{\rw}{\centering u1}
        };

        \node[indicator, right = 2cm of latent] at (2, \gap) (i2) {
          \parbox{\iw}{Runny Nose}
        };
        \node[residual, right = 0.5cm of i2] (u2) {
          \parbox{\rw}{\centering u2}
        };

        \node[indicator, right = 2cm of latent] at (2, -\gap) (i3) {
          \parbox{\iw}{Coughing}
        };
        \node[residual, right = 0.5cm of i3] (u3) {
          \parbox{\rw}{\centering u3}
        };

        \node[indicator, right = 2cm of latent] at (2, -3*\gap) (i4) {
          \parbox{\iw}{Fever}
        };
        \node[residual, right = 0.5cm of i4] (u4) {
          \parbox{\rw}{\centering u4}
        };

        %% Arrows
        \draw[double_arrow] ($(latent.north) + (0.39, 0)$) arc (-40:220:0.5);

        \draw[right_arrow] (latent.east) -- (i1.west);
        \draw[right_arrow] (latent.east) -- (i2.west);
        \draw[right_arrow] (latent.east) -- (i3.west);
        \draw[right_arrow] (latent.east) -- (i4.west);

        \draw[left_arrow] (i1.east) -- (u1.west);
        \draw[left_arrow] (i2.east) -- (u2.west);
        \draw[left_arrow] (i3.east) -- (u3.west);
        \draw[left_arrow] (i4.east) -- (u4.west);

        \draw[resid_arrow] ($(u1.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u2.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u3.east) + (0, 0.18)$) arc (150:-150:0.35);
        \draw[resid_arrow] ($(u4.east) + (0, 0.18)$) arc (150:-150:0.35);

      \end{tikzpicture}
    }
  \end{figure}

  \vspace{5mm}

  The latent viral infection is the causal factor that gives rise to the observed
  symptoms of illness.
  \begin{itemize}
    \item Symptoms are the dependent variables.
    \item Viral infection is the unobserved predictor variable.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Reflective Constructs}

  For reflective constructs, the underlying measurement model is a multivariate linear regression.
  \begin{itemize}
    \item The latent construct is the $X$ variable.
    \item The observed indicators are the $Y$ variables.
    \item The model reproduces the indicators via a system of linear equations.
  \end{itemize}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \scalebox{0.7}{
          \begin{tikzpicture}[
              indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
              factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
              residual/.style = {ellipse, draw = black, very thick, minimum size = 7mm},
              right_arrow/.style = {->, very thick},
              left_arrow/.style = {<-, very thick},
              double_arrow/.style = {<->, very thick},
              resid_arrow/.style = {<->, thick}
            ]
            \usetikzlibrary{shapes.geometric}

            %% Nodes
            \node[factor, draw] at (0, 0) (latent) {
              \parbox{\fw}{\centering Viral\\Infection}
            };
            \node[indicator, right = 1.5cm of latent] at (2, 3*\gap) (i1) {
              \parbox{\iw}{Muscle Ache}
            };
            \node[residual, right = 0.5cm of i1] (u1) {
              \parbox{\rw}{\centering u1}
            };

            \node[indicator, right = 1.5cm of latent] at (2, \gap) (i2) {
              \parbox{\iw}{Runny Nose}
            };
            \node[residual, right = 0.5cm of i2] (u2) {
              \parbox{\rw}{\centering u2}
            };

            \node[indicator, right = 1.5cm of latent] at (2, -\gap) (i3) {
              \parbox{\iw}{Coughing}
            };
            \node[residual, right = 0.5cm of i3] (u3) {
              \parbox{\rw}{\centering u3}
            };

            \node[indicator, right = 1.5cm of latent] at (2, -3*\gap) (i4) {
              \parbox{\iw}{Fever}
            };
            \node[residual, right = 0.5cm of i4] (u4) {
              \parbox{\rw}{\centering u4}
            };

            %% Arrows
            \draw[double_arrow] ($(latent.north) + (0.39, 0)$) arc (-40:220:0.5);

            \draw[right_arrow] (latent.east) -- (i1.west);
            \draw[right_arrow] (latent.east) -- (i2.west);
            \draw[right_arrow] (latent.east) -- (i3.west);
            \draw[right_arrow] (latent.east) -- (i4.west);

            \draw[left_arrow] (i1.east) -- (u1.west);
            \draw[left_arrow] (i2.east) -- (u2.west);
            \draw[left_arrow] (i3.east) -- (u3.west);
            \draw[left_arrow] (i4.east) -- (u4.west);

            \draw[resid_arrow] ($(u1.east) + (0, 0.18)$) arc (150:-150:0.35);
            \draw[resid_arrow] ($(u2.east) + (0, 0.18)$) arc (150:-150:0.35);
            \draw[resid_arrow] ($(u3.east) + (0, 0.18)$) arc (150:-150:0.35);
            \draw[resid_arrow] ($(u4.east) + (0, 0.18)$) arc (150:-150:0.35);

          \end{tikzpicture}
          }
        \end{figure}

      \end{column}
      \begin{column}{0.5\textwidth}
        \begin{align*}
          Y_{ache} &= \lambda_{11} \mathit{VI} + u_1\\
          Y_{nose} &= \lambda_{21} \mathit{VI} + u_2\\
          Y_{cough} &= \lambda_{31} \mathit{VI} + u_3\\
          Y_{fever} &= \lambda_{41} \mathit{VI} + u_4
        \end{align*}
      \end{column}
    \end{columns}

  \end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsubsection{Formative Constructs}

%----------------------------------------------------------------------------------------------------------------------%

\def\iw{25mm}\relax % Indicator node width
\def\fw{25mm}\relax % Factor node width

\begin{frame}{Formative Constructs}

  Flipping the direction of the factor loadings makes a \emph{formative construct}.

  \vb

  \begin{figure}
    \scalebox{0.7}{
      \begin{tikzpicture}[
          indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
          factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
          path/.style = {<-, very thick},
          double_arrow/.style = {<->, very thick},
          resid_arrow/.style = {<->, thick}
        ]
        \usetikzlibrary{shapes.geometric}

        %% Nodes
        \node[factor, draw] at (0, 0) (latent) {
          \parbox{\fw}{\centering Socioeconomic\\Status}
        };
        \node[indicator, right = 2cm of latent] at (2, 3*\gap) (i1) {
          \parbox{\iw}{Neighborhood}
        };
        \node[indicator, right = 2cm of latent] at (2, \gap) (i2) {
          \parbox{\iw}{Salary}
        };
        \node[indicator, right = 2cm of latent] at (2, -\gap) (i3) {
          \parbox{\iw}{Education}
        };
        \node[indicator, right = 2cm of latent] at (2, -3*\gap) (i4) {
          \parbox{\iw}{Occupation}
        };

        %% Arrows
        \draw[double_arrow] ($(latent.north) + (0.39, 0)$) arc (-40:220:0.5);

        \draw[path] (latent.9) -- (i1.west);
        \draw[path] (latent.3) -- (i2.west);
        \draw[path] (latent.357) -- (i3.west);
        \draw[path] (latent.351) -- (i4.west);

        \draw[resid_arrow] ($(i1.east) + (0.05, 0.15)$) arc (150:-150:0.3);
        \draw[resid_arrow] ($(i2.east) + (0.05, 0.15)$) arc (150:-150:0.3);
        \draw[resid_arrow] ($(i3.east) + (0.05, 0.15)$) arc (150:-150:0.3);
        \draw[resid_arrow] ($(i4.east) + (0.05, 0.15)$) arc (150:-150:0.3);

      \end{tikzpicture}
    }
  \end{figure}

  \vspace{5mm}

  SES is an \emph{index} defined as a (weighted) sum of the observed items.
  \begin{itemize}
    \item SES is the (latent) dependent variable, predicted by the items.
    \item This model is not empirically testable.
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\sectionslide{Technical Details}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Model Structure}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Diagram: Covariance Structure Model}

  The basic CFA only models the covariance structure.

  \begin{figure}
    \includegraphics[width = 0.9\textwidth]{figures/cfa_two_factors.pdf}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Matrices: Covariance Structure Model}

  \begin{columns}
    \begin{column}{0.7\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11} &           \\
          \psi_{21} & \psi_{22}
        \end{bmatrix}
        \\[12pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             &             &             &             &             &             &             \\
          0           & \theta_{22} &             &             &             &             &             &             &             \\
          0           & 0           & \theta_{33} &             &             &             &             &             &             \\
          0           & 0           & 0           & \theta_{44} &             &             &             &             &             \\
          0           & 0           & 0           & 0           & \theta_{55} &             &             &             &             \\
          0           & 0           & 0           & 0           & 0           & \theta_{66} &             &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & \theta_{77} &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{88} &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{99}
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.3\textwidth}
      \begin{align*}
        \\[22pt]
        \Lambda =
        \begin{bmatrix}
          \lambda_{11} & 0            \\
          \lambda_{21} & 0            \\
          \lambda_{31} & 0            \\
          \lambda_{41} & 0            \\
          0            & \lambda_{52} \\
          0            & \lambda_{62} \\
          0            & \lambda_{72} \\
          0            & \lambda_{82} \\
          0            & \lambda_{92}
        \end{bmatrix}
      \end{align*}
    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Diagram: Mean \& Covariance Structure}

  We can model the mean structure by including the latent means and item intercepts in our model.
  
  \begin{figure}
    \includegraphics[width = 0.9\textwidth]{figures/cfa_two_factors_means.pdf}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Matrices: Mean \& Covariance Structure}

  \begin{columns}
    \begin{column}{0.1\textwidth}
      \begin{align*}
        \alpha &=
        \begin{bmatrix}
          \alpha_1 \\
          \alpha_2
        \end{bmatrix}
        \\[12pt]
        \tau &=
        \begin{bmatrix}
          \tau_1 \\
          \tau_2 \\
          \tau_3 \\
          \tau_4 \\
          \tau_5 \\
          \tau_6 \\
          \tau_7 \\
          \tau_8 \\
          \tau_9
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.7\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11} &           \\
          \psi_{21} & \psi_{22}
        \end{bmatrix}
        \\[12pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             &             &             &             &             &             &             \\
          0           & \theta_{22} &             &             &             &             &             &             &             \\
          0           & 0           & \theta_{33} &             &             &             &             &             &             \\
          0           & 0           & 0           & \theta_{44} &             &             &             &             &             \\
          0           & 0           & 0           & 0           & \theta_{55} &             &             &             &             \\
          0           & 0           & 0           & 0           & 0           & \theta_{66} &             &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & \theta_{77} &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{88} &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{99}
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.2\textwidth}
      \begin{align*}
        \\[22pt]
        \Lambda =
        \begin{bmatrix}
          \lambda_{11} & 0            \\
          \lambda_{21} & 0            \\
          \lambda_{31} & 0            \\
          \lambda_{41} & 0            \\
          0            & \lambda_{52} \\
          0            & \lambda_{62} \\
          0            & \lambda_{72} \\
          0            & \lambda_{82} \\
          0            & \lambda_{92}
        \end{bmatrix}
      \end{align*}
    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Working Example}

  To keep things clear, let's start with a simpler example.

  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \\[12pt]
        \Lambda &=
        \begin{bmatrix}
          \lambda_{11}\\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \\[12pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.6\textwidth]{figures/cfa_three_indicators.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Degrees of Freedom}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Number of Estimated Parameters}

  \begin{columns}
    \begin{column}{0.6\textwidth}

      For this example, we need to estimate seven parameters to fully define the measurement model.
      \begin{itemize}
        \item One latent variance: $\psi_{11}$
        \item Three factor loadings: $\{ \lambda_{11}, \lambda_{21}, \lambda_{31} \}$
        \item Three residual variances: $\{ \theta_{11}, \theta_{22}, \theta_{33} \}$
      \end{itemize}

    \end{column}
    \begin{column}{0.4\textwidth}

      \begin{figure}
        \includegraphics[width = 0.8\textwidth]{figures/cfa_three_indicators.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{Available Information}

  The data only contain a fixed amount of information.
  \begin{itemize}
    \item We can quantify the available information in discrete units.
    \item Every unique element of $\mathrm{Cov}(\mathbf{Y})$ contributes one unit of information.
  \end{itemize}
  \begin{align*}
    \mathrm{Cov} ( \mathbf{Y} ) &=
    \begin{bmatrix*}[l]
      \var{y_1}      &                &           \\[3pt]
      \cov{y_2, y_1} & \var{y_2}      &           \\[3pt]
      \cov{y_3, y_1} & \cov{y_3, y_2} & \var{y_3} \\
    \end{bmatrix*}
  \end{align*}

  In this example, we have six pieces of available information.
  \begin{itemize}
    \item Three variances: $\var{y_1}$, $\var{y_2}$, $\var{y_3}$
    \item Three covariances: $\cov{y_2,y_1}$, $\cov{y_3,y_1}$, $\cov{y_3,y_2}$
  \end{itemize}

  \vb

  For a positive-definite $M \times M$ covariance matrix, the number of unique
  elements will always be $Q = \frac{M (M + 1)}{2}$.

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Degrees of Freedom}

  We can only estimate one parameter for each piece of available information, $Q$.
  \begin{itemize}
    \item We can estimate no more than $Q$ parameters in any one model.
  \end{itemize}

  \vb

  The \emph{degrees of freedom} (df) is the difference between the amount of
  information available in the data, $Q$, and the number of parameters
  estimated in our model, $P$. 
  \begin{align*}
    df = Q - P
  \end{align*}

  \vb

  If $df < 0$, the model is not estimable.
  \begin{itemize}
    \item A model with $df < 0$ is \emph{not identified}.
    \item The data do not provide enough information to define a unique solution
      for all $P$ parameter estimates.
  \end{itemize}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Degrees of Freedom}

  \begin{columns}
    \begin{column}{0.5\textwidth}

      What are the degrees of freedom for our example?
      \begin{align*}
        Q &= \frac{3 (3 + 1)}{2} = 6\\
        df &= Q - P = 6 - 7 = -1
      \end{align*}
      This model has negative $df$.
      \begin{itemize}
        \item We cannot estimate the model in this form.
        \item We must impose \emph{identifying constraints}.
      \end{itemize}

    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.65\textwidth]{figures/cfa_three_indicators.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\subsection{Model Identification}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{Identifying Constraints}

  Consider the following equation:
  \begin{align*}
    5 = x + y
  \end{align*}
  What are the values of $x$ and $y$?
  \pause
  \begin{align*}
    y = 5 - x
  \end{align*}
  \pause
  What if we assume that $y = x$?
  \pause
  \begin{align*}
    5 &= x + y\\
    0 &= x - y
  \end{align*}
  \pause
  Now we have enough information:
  \begin{align*}
    5 = x + x = 2x~~\Rightarrow~~x = y = 2.5
  \end{align*}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Identifying Constraints}

  We must fix some parameters to identify the model.
  \begin{itemize}
    \item For each construct, we need $df \geq 0$.
      \vc
    \item If the construct has three or more indicators:
      \begin{itemize}
        \item Fix one parameter in the covariance model.
        \item Fix one parameter in the mean model.
      \end{itemize}
      \vc
    \item If the construct has two indicators:
      \begin{itemize}
        \item Fix an additional parameter in the covariance model.
      \end{itemize}
      \vc
    \item If the construct has only one indicator:
      \begin{itemize}
        \item Cannot define a latent factor.
      \end{itemize}
  \end{itemize}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Identifying Constraints}

  These constraints also define the scale of the latent factors.
  \begin{itemize}
    \item Latent factors have no direct representation as observed variables in our dataset.
    \item A latent factor only exists after we've estimated it.
    \item So latent factors have no inherent scale.
    \item Identifying constraints are also called \emph{scaling constraints}.
  \end{itemize}

  \vb

  There are two common methods of identifying/scaling CFA models.
  \begin{enumerate}
    \item Marker-variable method
    \item Fixed-factor method
  \end{enumerate}

\end{frame}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{Unconstrained Model}

  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          \lambda_{11}\\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
        \\[8pt]
        Q &= \frac{3 (3 + 1)}{2} = 6
        \\[8pt]
        df &= Q - P\\
           &= 6 - 7 = -1
      \end{align*}
    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.65\textwidth]{figures/cfa_three_indicators.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Marker-Variable Method}

  Constrain the covariance model by fixing one factor loading to 1.

  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          1           \\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
        \\[8pt]
        df &= Q - P\\
           &= 6 - 6 = 0
      \end{align*}
    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.6\textwidth]{figures/marker_variable.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Fixed-Factor Method}

  Constrain the covariance model by fixing one factor variance to 1.

  \begin{columns}
    \begin{column}{0.5\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          1
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          \lambda_{11}\\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
        \\[8pt]
        df &= Q - P\\
           &= 6 - 6 = 0
      \end{align*}
    \end{column}
    \begin{column}{0.5\textwidth}

      \begin{figure}
        \includegraphics[width = 0.6\textwidth]{figures/fixed_factor.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Unconstrained Model with Means}

  \begin{columns}
    \begin{column}{0.4\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \quad
        \alpha =
        \begin{bmatrix}
          \alpha_1
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          \lambda_{11}\\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \quad
        \tau =
        \begin{bmatrix}
          \tau_1 \\
          \tau_2 \\
          \tau_3
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
        \\[8pt]
        Q &= \frac{3 (3 + 1)}{2} + 3 = 9\\[8pt]
        df &= Q - P\\
           &= 9 - 11 = -2
      \end{align*}
    \end{column}
    \begin{column}{0.6\textwidth}

      \begin{figure}
        \includegraphics[width = 0.65\textwidth]{figures/cfa_three_indicators_means.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Marker-Variable with Means}

  Constrain the mean model by fixing the latent mean to zero.

  \begin{columns}
    \begin{column}{0.4\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \quad
        \alpha =
        \begin{bmatrix}
          0
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          1           \\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \quad
        \tau =
        \begin{bmatrix}
          \tau_1 \\
          \tau_2 \\
          \tau_3
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
        \\[8pt]
        df &= Q - P\\
           &= 9 - 9 = 0
      \end{align*}
    \end{column}
    \begin{column}{0.6\textwidth}

      \begin{figure}
        \includegraphics[width = 0.65\textwidth]{figures/marker_variable_means.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Marker-Variable with Means}

  Constrain the mean model by fixing one item intercept to zero.

  \begin{columns}
    \begin{column}{0.4\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11}
        \end{bmatrix}
        \quad
        \alpha =
        \begin{bmatrix}
          \alpha_1
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          1           \\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \quad
        \tau =
        \begin{bmatrix}
          0      \\
          \tau_2 \\
          \tau_3
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
        \\[8pt]
        df &= Q - P\\
           &= 9 - 9 = 0
      \end{align*}
    \end{column}
    \begin{column}{0.6\textwidth}

      \begin{figure}
        \includegraphics[width = 0.65\textwidth]{figures/marker_variable_means_alt.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Fixed-Factor with Means}

  Constrain the mean model by fixing the latent mean to zero.

  \begin{columns}
    \begin{column}{0.4\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          1
        \end{bmatrix}
        \quad
        \alpha =
        \begin{bmatrix}
          0
        \end{bmatrix}
        \\[8pt]
        \Lambda &=
        \begin{bmatrix}
          \lambda_{11}\\
          \lambda_{21}\\
          \lambda_{31}
        \end{bmatrix}
        \quad
        \tau =
        \begin{bmatrix}
          \tau_1\\
          \tau_2\\
          \tau_3
        \end{bmatrix}
        \\[8pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             \\
          0           & \theta_{22} &             \\
          0           & 0           & \theta_{33}
        \end{bmatrix}
        \\[8pt]
        df &= Q - P\\
           &= 9 - 9 = 0
      \end{align*}
    \end{column}
    \begin{column}{0.6\textwidth}

      \begin{figure}
        \includegraphics[width = 0.65\textwidth]{figures/fixed_factor_means.pdf}
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Two Construct: Unconstrained Model}
  
  \begin{figure}
    \includegraphics[width = 0.9\textwidth]{figures/cfa_two_factors_means.pdf}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Unconstrained Parameter Matrices}

  \begin{columns}
    \begin{column}{0.1\textwidth}
      \begin{align*}
        \alpha &=
        \begin{bmatrix}
          \alpha_1 \\
          \alpha_2
        \end{bmatrix}
        \\[12pt]
        \tau &=
        \begin{bmatrix}
          \tau_1 \\
          \tau_2 \\
          \tau_3 \\
          \tau_4 \\
          \tau_5 \\
          \tau_6 \\
          \tau_7 \\
          \tau_8 \\
          \tau_9
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.7\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11} &           \\
          \psi_{21} & \psi_{22}
        \end{bmatrix}
        \\[12pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             &             &             &             &             &             &             \\
          0           & \theta_{22} &             &             &             &             &             &             &             \\
          0           & 0           & \theta_{33} &             &             &             &             &             &             \\
          0           & 0           & 0           & \theta_{44} &             &             &             &             &             \\
          0           & 0           & 0           & 0           & \theta_{55} &             &             &             &             \\
          0           & 0           & 0           & 0           & 0           & \theta_{66} &             &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & \theta_{77} &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{88} &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{99}
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.2\textwidth}
      \begin{align*}
        \\[22pt]
        \Lambda =
        \begin{bmatrix}
          \lambda_{11} & 0            \\
          \lambda_{21} & 0            \\
          \lambda_{31} & 0            \\
          \lambda_{41} & 0            \\
          0            & \lambda_{52} \\
          0            & \lambda_{62} \\
          0            & \lambda_{72} \\
          0            & \lambda_{82} \\
          0            & \lambda_{92}
        \end{bmatrix}
      \end{align*}
    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Two Construct: Marker Variable}
  
  \begin{figure}
    \includegraphics[width = 0.9\textwidth]{figures/marker_variable_two_factors_means.pdf}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Parameter Matrices: Marker Variable}

  \begin{columns}
    \begin{column}{0.1\textwidth}
      \begin{align*}
        \alpha &=
        \begin{bmatrix}
          0\\
          0
        \end{bmatrix}
        \\[12pt]
        \tau &=
        \begin{bmatrix}
          \tau_1 \\
          \tau_2 \\
          \tau_3 \\
          \tau_4 \\
          \tau_5 \\
          \tau_6 \\
          \tau_7 \\
          \tau_8 \\
          \tau_9
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.7\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          \psi_{11} &           \\
          \psi_{21} & \psi_{22}
        \end{bmatrix}
        \\[12pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             &             &             &             &             &             &             \\
          0           & \theta_{22} &             &             &             &             &             &             &             \\
          0           & 0           & \theta_{33} &             &             &             &             &             &             \\
          0           & 0           & 0           & \theta_{44} &             &             &             &             &             \\
          0           & 0           & 0           & 0           & \theta_{55} &             &             &             &             \\
          0           & 0           & 0           & 0           & 0           & \theta_{66} &             &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & \theta_{77} &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{88} &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{99}
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.2\textwidth}
      \begin{align*}
        \\[22pt]
        \Lambda =
        \begin{bmatrix}
          1            & 0            \\
          \lambda_{21} & 0            \\
          \lambda_{31} & 0            \\
          \lambda_{41} & 0            \\
          0            & 1            \\
          0            & \lambda_{62} \\
          0            & \lambda_{72} \\
          0            & \lambda_{82} \\
          0            & \lambda_{92}
        \end{bmatrix}
      \end{align*}
    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Two Construct: Fixed-Factor}
  
  \begin{figure}
    \includegraphics[width = 0.9\textwidth]{figures/fixed_factor_two_factors_means.pdf}
  \end{figure}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}{Parameter Matrices: Fixed-Factor}

  \begin{columns}
    \begin{column}{0.1\textwidth}
      \begin{align*}
        \alpha &=
        \begin{bmatrix}
          0\\
          0
        \end{bmatrix}
        \\[12pt]
        \tau &=
        \begin{bmatrix}
          \tau_1 \\
          \tau_2 \\
          \tau_3 \\
          \tau_4 \\
          \tau_5 \\
          \tau_6 \\
          \tau_7 \\
          \tau_8 \\
          \tau_9
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.7\textwidth}
      \begin{align*}
        \Psi &=
        \begin{bmatrix}
          1         &  \\
          \psi_{21} & 1
        \end{bmatrix}
        \\[12pt]
        \Theta &=
        \begin{bmatrix}
          \theta_{11} &             &             &             &             &             &             &             &             \\
          0           & \theta_{22} &             &             &             &             &             &             &             \\
          0           & 0           & \theta_{33} &             &             &             &             &             &             \\
          0           & 0           & 0           & \theta_{44} &             &             &             &             &             \\
          0           & 0           & 0           & 0           & \theta_{55} &             &             &             &             \\
          0           & 0           & 0           & 0           & 0           & \theta_{66} &             &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & \theta_{77} &             &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{88} &             \\
          0           & 0           & 0           & 0           & 0           & 0           & 0           & 0           & \theta_{99}
        \end{bmatrix}
      \end{align*}
    \end{column}
    \begin{column}{0.2\textwidth}
      \begin{align*}
        \\[22pt]
        \Lambda =
        \begin{bmatrix}
          \lambda_{11} & 0            \\
          \lambda_{21} & 0            \\
          \lambda_{31} & 0            \\
          \lambda_{41} & 0            \\
          0            & \lambda_{52} \\
          0            & \lambda_{62} \\
          0            & \lambda_{72} \\
          0            & \lambda_{82} \\
          0            & \lambda_{92}
        \end{bmatrix}
      \end{align*}
    \end{column}
  \end{columns}

\end{frame}


\watermarkon %---------------------------------------------------------------------------------------------------------%

\sectionslide{Example}

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{South African Personality Inventory Project}

  \begin{figure}[c]
    \includegraphics[width = 0.9\textwidth]{SAPI.png}
  \end{figure}
	
\end{frame}

\watermarkon %---------------------------------------------------------------------------------------------------------%

\begin{frame}{SAPI details}
	\begin{itemize}
		\item 1216 participants from 11 official language groups
		\item From about 50,000 descriptive responses to 262 personality items
		\item Nine personality clusters: 
		\begin{itemize}
			\item Conscientiousness
			\item Emotional Stability
			\item Extraversion
			\item Facilitating
			\item Integrity
			\item Intellect
			\item Openness
			\item Relationship Harmony
			\item Soft-Heartedness (Ubuntu)
		\end{itemize}
		\item Our data: selection of 1000 participants
	\end{itemize}
\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\def\iw{45mm}\relax     % Indicator node width
\def\fw{20mm}\relax     % Factor node width
\def\gap{0.6}\relax     % Spread between indicator nodes
\def\offset{30mm}\relax % Vertical offset between construct submodels

\watermarkoff %--------------------------------------------------------------------------------------------------------%

\begin{frame}{CFA of Extraversion Items}

  \begin{columns}
    \begin{column}{0.45\textwidth}

      Suppose we hypothesize two distinct dimensions of extraversion underlying
      8 of the SAPI items.
      \begin{enumerate}
        \item Having Fun
        \item Being Liked by Others
      \end{enumerate}
      \vb
      We'll define our measurement model as the two-factor CFA shown to the right.

    \end{column}
    \begin{column}{0.55\textwidth}

      \begin{figure}
        \scalebox{0.5}{
          \begin{tikzpicture}[
              indicator/.style = {rectangle, draw = black, very thick, minimum size = 7mm},
              factor/.style = {ellipse, draw = black, very thick, minimum size = 10mm},
              reg/.style = {->, very thick},
              cov/.style = {<->, very thick}
            ]
            \usetikzlibrary{shapes.geometric}

            %% F1 Nodes
            \node[factor, draw, yshift = \offset] at (0, 0) (f1) {
              \parbox{\fw}{\centering Having\\Fun}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, 3*\gap) (i1) {
              \parbox{\iw}{Item 77:\\I enjoy telling funny stories}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, \gap) (i2) {
              \parbox{\iw}{Item 84:\\I am a good storyteller}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -\gap) (i3) {
              \parbox{\iw}{Item 170:\\I laugh a lot}
            };
            \node[indicator, right = 2cm of f1, yshift = \offset] at (2, -3*\gap) (i4) {
              \parbox{\iw}{Item 196:\\I make others laugh}
            };

            %% F1 Arrows
            \draw[reg] (f1.east) -- (i1.west);
            \draw[reg] (f1.east) -- (i2.west);
            \draw[reg] (f1.east) -- (i3.west);
            \draw[reg] (f1.east) -- (i4.west);

            %% F2 Nodes
            \node[factor, draw, yshift = -\offset] at (0, 0) (f2) {
              \parbox{\fw}{\centering Being\\Liked}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, 3*\gap) (i5) {
              \parbox{\iw}{Item 44:\\I am liked by everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, \gap) (i6) {
              \parbox{\iw}{Item 63:\\I chat to everyone}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -\gap) (i7) {
              \parbox{\iw}{Item 76:\\I have many friends}
            };
            \node[indicator, right = 2cm of f2, yshift = -\offset] at (2, -3*\gap) (i8) {
              \parbox{\iw}{Item 98:\\I have good social skills}
            };

            %% F2 Arrows
            \draw[reg] (f2.east) -- (i5.west);
            \draw[reg] (f2.east) -- (i6.west);
            \draw[reg] (f2.east) -- (i7.west);
            \draw[reg] (f2.east) -- (i8.west);

            %% Latent Covariance
            \path[cov] (f1.west) edge [bend right] (f2.west);

          \end{tikzpicture}
        }
      \end{figure}

    \end{column}
  \end{columns}

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Marker Variable}

  Load the SAPI data.

<<>>=
dataDir <- "data"
sapi <- read.table(here::here(dataDir, "sapi.txt"),
                   header = TRUE,
                   na.strings = "-999")
@

  Specify the \pkg{lavaan} model syntax for the SAPI extraversion CFA.

<<>>=
mod1 <- '
fun   =~ Q77 + Q84 + Q170 + Q196 
liked =~ Q44 + Q63 + Q76  + Q98
'
@

Use the \src{cfa()} function to estimate the model.

<<>>=
library(lavaan)
out1 <- cfa(mod1, data = sapi)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Marker Variable}

<<>>=
partSummary(out1, 1:4)
@

\framebreak

<<>>=
partSummary(out1, 5:7)
@

\framebreak

<<>>=
partSummary(out1, 8:9)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%
\comment{%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile, allowframebreaks]{Example: Marker Variable}

<<>>=
inspect(out1, "r2")
fitMeasures(out1) |> head(22) |> round(3)
@

\framebreak

<<>>=
fitMeasures(out1) |> tail(-22) |> round(3)
@

\end{frame}
}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Fixed Factor}

  We only need to change one option to implement the fixed-factor method.
  \begin{itemize}
    \item The \src{std.lv = TRUE} option (i.e., standardized latent variables)
      applies the appropriate constraints.
  \end{itemize}

<<>>=
out2 <- cfa(mod1, data = sapi, std.lv = TRUE)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Example: Fixed Factor}

<<>>=
partSummary(out2, 1:4)
@

\framebreak

<<>>=
partSummary(out2, 5:7)
@

\framebreak

<<>>=
partSummary(out2, 8:9)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%
\comment{%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile, allowframebreaks]{Example: Fixed Factor}

<<>>=
inspect(out2, "r2")
fitMeasures(out2) |> head(22) |> round(3)
@

\framebreak

<<>>=
fitMeasures(out2) |> tail(-22) |> round(3)
@

\end{frame}

%----------------------------------------------------------------------------------------------------------------------%

\begin{frame}[fragile, allowframebreaks]{Compare Results}

<<>>=
inspect(out1, "est")$lambda - inspect(out2, "est")$lambda
inspect(out1, "est")$psi - inspect(out2, "est")$psi
@

\framebreak

<<>>=
all.equal(fitMeasures(out1), fitMeasures(out2))
inspect(out1, "r2") - inspect(out2, "r2")
inspect(out1, "est")$theta - inspect(out2, "est")$theta
@

\end{frame}
}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%----------------------------------------------------------------------------------------------------------------------%

\end{document}
